### PR TITLE
virtual/rust and friends: Add 1.80.0

### PR DESCRIPTION
**Pull request by bowlofeggs**
Add Rust 1.80.0 to the tree.

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by bowlofeggs** [comment]
I've noticed a few packages that seem to fail to build due to `time` with this update, such as `bottom` and `starship`. It looks like this was reported upstream already, and they have opted to declare that packages just need to use a new version of time: https://github.com/rust-lang/rust/issues/127343

**Comment by ionenwks** [comment]
> I've noticed a few packages that seem to fail to build due to `time` with this update, such as `bottom` and `starship`. It looks like this was reported upstream already, and they have opted to declare that packages just need to use a new version of time: [rust-lang/rust#127343](https://github.com/rust-lang/rust/issues/127343)

Do all packages with `<time-0.3.35` fail or only some of them? From quick grep this is all the packages using time, only a few have a version with `>=0.3.35` with the linked fix (this wouldn't catch vendored crates like starship's too).

<details>
  <summary>(click to see list)</summary>

```
app-backup/rdedup/rdedup-1.0.2-r1.ebuild:	time@0.1.45
app-crypt/sequoia-chameleon-gnupg/sequoia-chameleon-gnupg-0.10.0.ebuild:	time@0.3.36
app-crypt/sequoia-chameleon-gnupg/sequoia-chameleon-gnupg-0.10.1.ebuild:	time@0.3.36
app-crypt/sequoia-chameleon-gnupg/sequoia-chameleon-gnupg-0.8.0.ebuild:	time@0.3.34
app-crypt/sequoia-chameleon-gnupg/sequoia-chameleon-gnupg-0.9.0.ebuild:	time@0.3.36
app-crypt/sequoia-sq/sequoia-sq-0.35.0.ebuild:	time@0.3.36
app-crypt/sequoia-sq/sequoia-sq-0.36.0.ebuild:	time@0.3.36
app-crypt/sequoia-sq/sequoia-sq-0.37.0.ebuild:	time@0.3.36
app-editors/helix/helix-24.03-r1.ebuild:	time@0.3.23
app-editors/helix/helix-24.07.ebuild:	time@0.3.36
app-emulation/ruffle/ruffle-0_p20240622.ebuild:	time@0.3.36
app-emulation/ruffle/ruffle-0_p20240722.ebuild:	time@0.3.36
app-emulation/virtiofsd/virtiofsd-1.10.0.ebuild:	time@0.3.11
app-emulation/virtiofsd/virtiofsd-1.10.1.ebuild:	time@0.3.11
app-emulation/virtiofsd/virtiofsd-9999.ebuild:	time@0.3.11
app-forensics/yara-x/yara-x-0.4.0.ebuild:	time@0.3.36
app-i18n/yaskkserv2/yaskkserv2-0.1.7.ebuild:	time-0.1.45
app-misc/anki/anki-24.04.1.ebuild:	time@0.3.34
app-misc/broot/broot-1.36.1.ebuild:time@0.3.34
app-misc/broot/broot-1.39.0.ebuild:time@0.3.36
app-misc/broot/broot-1.39.1.ebuild:time@0.3.36
app-misc/jaq/jaq-1.4.0.ebuild:	time@0.3.20
app-misc/jaq/jaq-1.5.0.ebuild:	time@0.3.20
app-misc/skim/skim-0.10.4.ebuild:	time@0.1.44
app-misc/skim/skim-0.10.4.ebuild:	time@0.3.15
app-misc/weggli/weggli-0.2.4.ebuild:	time-0.1.44
app-misc/zellij/zellij-0.40.1-r1.ebuild:	time@0.1.44
app-misc/zellij/zellij-0.40.1-r1.ebuild:	time@0.2.27
app-portage/emlop/emlop-0.6.1.ebuild:	time-0.3.22
app-portage/emlop/emlop-0.7.0.ebuild:	time@0.3.34
app-shells/atuin/atuin-18.2.0.ebuild:	time@0.3.34
app-shells/atuin/atuin-18.3.0-r1.ebuild:	time@0.3.36
app-shells/mcfly/mcfly-0.5.13.ebuild:	time-0.1.43
app-shells/nushell/nushell-0.85.0.ebuild:	time@0.3.22
app-shells/nushell/nushell-0.91.0.ebuild:	time@0.3.31
app-shells/nushell/nushell-0.93.0.ebuild:	time@0.3.34
app-shells/nushell/nushell-0.94.2.ebuild:	time@0.3.36
app-shells/nushell/nushell-0.95.0.ebuild:	time@0.3.36
app-shells/starship/starship-1.17.1.ebuild:	time@0.3.31
dev-python/pyproject-fmt-rust/pyproject-fmt-rust-1.1.3.ebuild:	time@0.3.36
dev-python/pyproject-fmt-rust/pyproject-fmt-rust-1.1.4.ebuild:	time@0.3.36
dev-python/pyproject-fmt-rust/pyproject-fmt-rust-1.1.5.ebuild:	time@0.3.36
dev-util/bingrep/bingrep-0.10.1.ebuild:	time-0.1.44
dev-util/cargo-c/cargo-c-0.10.0.ebuild:	time@0.3.36
dev-util/cargo-c/cargo-c-0.9.30.ebuild:	time@0.3.34
dev-util/cargo-c/cargo-c-0.9.31.ebuild:	time@0.3.34
dev-util/cargo-c/cargo-c-0.9.32.ebuild:	time@0.3.36
dev-util/cargo-ebuild/cargo-ebuild-0.5.4-r1.ebuild:	time@0.3.17
dev-util/elfshaker/elfshaker-0.9.0_p20230918.ebuild:	time@0.1.45
dev-util/elfshaker/elfshaker-0.9.0_p20240122.ebuild:	time@0.1.45
dev-util/git-delta/git-delta-0.16.5.ebuild:	time@0.1.45
dev-util/git-delta/git-delta-0.16.5.ebuild:	time@0.3.20
dev-util/git-delta/git-delta-0.17.0.ebuild:	time@0.3.31
dev-util/maturin/maturin-1.6.0.ebuild:	time@0.3.34
dev-util/maturin/maturin-1.7.0.ebuild:	time@0.3.36
dev-util/py-spy/py-spy-0.3.14.ebuild:	time-0.1.44
dev-util/rustup/rustup-1.25.2.ebuild:	time@0.1.43
dev-util/rustup/rustup-1.25.2.ebuild:	time@0.3.9
dev-util/sccache/sccache-0.5.4-r1.ebuild:	time@0.1.43
dev-util/sccache/sccache-0.5.4-r1.ebuild:	time@0.3.17
dev-util/selenium-manager/selenium-manager-4.14.0.ebuild:	time@0.3.23
dev-util/selenium-manager/selenium-manager-4.15.0.ebuild:	time@0.3.23
dev-util/wachy/wachy-0.1.0_alpha6-r1.ebuild:	time@0.1.43
dev-util/wachy/wachy-0.1.0_alpha6-r1.ebuild:	time@0.3.5
dev-util/wasmer/wasmer-0.11.0.ebuild:	time@0.1.42
dev-vcs/git-absorb/git-absorb-0.6.13-r1.ebuild:	time@0.3.34
dev-vcs/git-absorb/git-absorb-0.6.15.ebuild:	time@0.3.36
dev-vcs/mercurial/mercurial-6.5.3.ebuild:	time-0.1.44
dev-vcs/mercurial/mercurial-6.6.2.ebuild:	time@0.1.44
dev-vcs/stgit/stgit-2.4.6.ebuild:	time-0.3.34
dev-vcs/stgit/stgit-2.4.7.ebuild:	time@0.3.36
games-strategy/ja2-stracciatella/ja2-stracciatella-0.21.0.ebuild:time@0.3.15
gnome-base/librsvg/librsvg-2.57.0.ebuild:	time@0.3.28
gnome-base/librsvg/librsvg-2.57.2.ebuild:	time@0.3.30
gnome-base/librsvg/librsvg-2.57.3.ebuild:	time@0.3.30
gui-apps/tuigreet/tuigreet-0.8.0-r1.ebuild:	time-0.1.43
gui-apps/tuigreet/tuigreet-0.9.1.ebuild:	time@0.3.36
media-sound/ncspot/ncspot-1.1.1.ebuild:	time@0.3.36
media-sound/ncspot/ncspot-1.1.2.ebuild:	time@0.3.36
net-analyzer/trippy/trippy-0.10.0.ebuild:	time@0.3.34
net-libs/quiche/quiche-0.22.0.ebuild:time@0.3.34
net-libs/quiche/quiche-9999.ebuild:time@0.3.34
net-misc/geckodriver/geckodriver-0.34.0.ebuild:	time@0.3.31
net-misc/websocat/websocat-1.11.0.ebuild:	time-0.1.44
net-misc/zerotier/zerotier-1.12.2.ebuild:	time@0.3.25
net-misc/zerotier/zerotier-1.14.0.ebuild:	time@0.3.34
net-p2p/arti/arti-1.2.5.ebuild:	time@0.3.36
sys-apps/amdgpu_top/amdgpu_top-0.7.0.ebuild:	time@0.3.34
sys-apps/bat/bat-0.23.0-r1.ebuild:	time@0.3.14
sys-apps/bat/bat-0.24.0-r1.ebuild:	time@0.3.14
sys-apps/eza/eza-0.18.13.ebuild:	time@0.3.30
sys-apps/eza/eza-0.18.16.ebuild:	time@0.3.30
sys-apps/eza/eza-0.18.21.ebuild:	time@0.3.30
sys-apps/eza/eza-0.18.6.ebuild:	time@0.3.30
sys-apps/uutils-coreutils/uutils-coreutils-0.0.25.ebuild:	time@0.3.20
sys-apps/uutils-coreutils/uutils-coreutils-0.0.27.ebuild:	time@0.3.36
sys-apps/uutils-coreutils/uutils-coreutils-9999.ebuild:	time@0.3.36
sys-apps/uutils-findutils/uutils-findutils-0.4.2-r1.ebuild:	time@0.3.30
sys-power/wluma/wluma-4.3.0-r2.ebuild:	time@0.1.45
sys-process/below/below-0.7.0.ebuild:	time-0.3.16
sys-process/below/below-0.7.1.ebuild:	time@0.3.16
sys-process/below/below-0.8.1.ebuild:	time@0.3.16
sys-process/bottom/bottom-0.9.6.ebuild:	time-0.3.27
x11-terms/wezterm/wezterm-20240203.110809-r1.ebuild:	time@0.3.31
evan@eos:~/tmp$ vim log
evan@eos:~/tmp$ vim log
evan@eos:~/tmp$ cat log
app-backup/rdedup/rdedup-1.0.2-r1.ebuild:	time@0.1.45
app-crypt/sequoia-chameleon-gnupg/sequoia-chameleon-gnupg-0.10.0.ebuild:	time@0.3.36
app-crypt/sequoia-chameleon-gnupg/sequoia-chameleon-gnupg-0.10.1.ebuild:	time@0.3.36
app-crypt/sequoia-chameleon-gnupg/sequoia-chameleon-gnupg-0.8.0.ebuild:	time@0.3.34
app-crypt/sequoia-chameleon-gnupg/sequoia-chameleon-gnupg-0.9.0.ebuild:	time@0.3.36
app-crypt/sequoia-sq/sequoia-sq-0.35.0.ebuild:	time@0.3.36
app-crypt/sequoia-sq/sequoia-sq-0.36.0.ebuild:	time@0.3.36
app-crypt/sequoia-sq/sequoia-sq-0.37.0.ebuild:	time@0.3.36
app-editors/helix/helix-24.03-r1.ebuild:	time@0.3.23
app-editors/helix/helix-24.07.ebuild:	time@0.3.36
app-emulation/ruffle/ruffle-0_p20240622.ebuild:	time@0.3.36
app-emulation/ruffle/ruffle-0_p20240722.ebuild:	time@0.3.36
app-emulation/virtiofsd/virtiofsd-1.10.0.ebuild:	time@0.3.11
app-emulation/virtiofsd/virtiofsd-1.10.1.ebuild:	time@0.3.11
app-emulation/virtiofsd/virtiofsd-9999.ebuild:	time@0.3.11
app-forensics/yara-x/yara-x-0.4.0.ebuild:	time@0.3.36
app-i18n/yaskkserv2/yaskkserv2-0.1.7.ebuild:	time-0.1.45
app-misc/anki/anki-24.04.1.ebuild:	time@0.3.34
app-misc/broot/broot-1.36.1.ebuild:time@0.3.34
app-misc/broot/broot-1.39.0.ebuild:time@0.3.36
app-misc/broot/broot-1.39.1.ebuild:time@0.3.36
app-misc/jaq/jaq-1.4.0.ebuild:	time@0.3.20
app-misc/jaq/jaq-1.5.0.ebuild:	time@0.3.20
app-misc/skim/skim-0.10.4.ebuild:	time@0.1.44
app-misc/skim/skim-0.10.4.ebuild:	time@0.3.15
app-misc/weggli/weggli-0.2.4.ebuild:	time-0.1.44
app-misc/zellij/zellij-0.40.1-r1.ebuild:	time@0.1.44
app-misc/zellij/zellij-0.40.1-r1.ebuild:	time@0.2.27
app-portage/emlop/emlop-0.6.1.ebuild:	time-0.3.22
app-portage/emlop/emlop-0.7.0.ebuild:	time@0.3.34
app-shells/atuin/atuin-18.2.0.ebuild:	time@0.3.34
app-shells/atuin/atuin-18.3.0-r1.ebuild:	time@0.3.36
app-shells/mcfly/mcfly-0.5.13.ebuild:	time-0.1.43
app-shells/nushell/nushell-0.85.0.ebuild:	time@0.3.22
app-shells/nushell/nushell-0.91.0.ebuild:	time@0.3.31
app-shells/nushell/nushell-0.93.0.ebuild:	time@0.3.34
app-shells/nushell/nushell-0.94.2.ebuild:	time@0.3.36
app-shells/nushell/nushell-0.95.0.ebuild:	time@0.3.36
app-shells/starship/starship-1.17.1.ebuild:	time@0.3.31
dev-python/pyproject-fmt-rust/pyproject-fmt-rust-1.1.3.ebuild:	time@0.3.36
dev-python/pyproject-fmt-rust/pyproject-fmt-rust-1.1.4.ebuild:	time@0.3.36
dev-python/pyproject-fmt-rust/pyproject-fmt-rust-1.1.5.ebuild:	time@0.3.36
dev-util/bingrep/bingrep-0.10.1.ebuild:	time-0.1.44
dev-util/cargo-c/cargo-c-0.10.0.ebuild:	time@0.3.36
dev-util/cargo-c/cargo-c-0.9.30.ebuild:	time@0.3.34
dev-util/cargo-c/cargo-c-0.9.31.ebuild:	time@0.3.34
dev-util/cargo-c/cargo-c-0.9.32.ebuild:	time@0.3.36
dev-util/cargo-ebuild/cargo-ebuild-0.5.4-r1.ebuild:	time@0.3.17
dev-util/elfshaker/elfshaker-0.9.0_p20230918.ebuild:	time@0.1.45
dev-util/elfshaker/elfshaker-0.9.0_p20240122.ebuild:	time@0.1.45
dev-util/git-delta/git-delta-0.16.5.ebuild:	time@0.1.45
dev-util/git-delta/git-delta-0.16.5.ebuild:	time@0.3.20
dev-util/git-delta/git-delta-0.17.0.ebuild:	time@0.3.31
dev-util/maturin/maturin-1.6.0.ebuild:	time@0.3.34
dev-util/maturin/maturin-1.7.0.ebuild:	time@0.3.36
dev-util/py-spy/py-spy-0.3.14.ebuild:	time-0.1.44
dev-util/rustup/rustup-1.25.2.ebuild:	time@0.1.43
dev-util/rustup/rustup-1.25.2.ebuild:	time@0.3.9
dev-util/sccache/sccache-0.5.4-r1.ebuild:	time@0.1.43
dev-util/sccache/sccache-0.5.4-r1.ebuild:	time@0.3.17
dev-util/selenium-manager/selenium-manager-4.14.0.ebuild:	time@0.3.23
dev-util/selenium-manager/selenium-manager-4.15.0.ebuild:	time@0.3.23
dev-util/wachy/wachy-0.1.0_alpha6-r1.ebuild:	time@0.1.43
dev-util/wachy/wachy-0.1.0_alpha6-r1.ebuild:	time@0.3.5
dev-util/wasmer/wasmer-0.11.0.ebuild:	time@0.1.42
dev-vcs/git-absorb/git-absorb-0.6.13-r1.ebuild:	time@0.3.34
dev-vcs/git-absorb/git-absorb-0.6.15.ebuild:	time@0.3.36
dev-vcs/mercurial/mercurial-6.5.3.ebuild:	time-0.1.44
dev-vcs/mercurial/mercurial-6.6.2.ebuild:	time@0.1.44
dev-vcs/stgit/stgit-2.4.6.ebuild:	time-0.3.34
dev-vcs/stgit/stgit-2.4.7.ebuild:	time@0.3.36
games-strategy/ja2-stracciatella/ja2-stracciatella-0.21.0.ebuild:time@0.3.15
gnome-base/librsvg/librsvg-2.57.0.ebuild:	time@0.3.28
gnome-base/librsvg/librsvg-2.57.2.ebuild:	time@0.3.30
gnome-base/librsvg/librsvg-2.57.3.ebuild:	time@0.3.30
gui-apps/tuigreet/tuigreet-0.8.0-r1.ebuild:	time-0.1.43
gui-apps/tuigreet/tuigreet-0.9.1.ebuild:	time@0.3.36
media-sound/ncspot/ncspot-1.1.1.ebuild:	time@0.3.36
media-sound/ncspot/ncspot-1.1.2.ebuild:	time@0.3.36
net-analyzer/trippy/trippy-0.10.0.ebuild:	time@0.3.34
net-libs/quiche/quiche-0.22.0.ebuild:time@0.3.34
net-libs/quiche/quiche-9999.ebuild:time@0.3.34
net-misc/geckodriver/geckodriver-0.34.0.ebuild:	time@0.3.31
net-misc/websocat/websocat-1.11.0.ebuild:	time-0.1.44
net-misc/zerotier/zerotier-1.12.2.ebuild:	time@0.3.25
net-misc/zerotier/zerotier-1.14.0.ebuild:	time@0.3.34
net-p2p/arti/arti-1.2.5.ebuild:	time@0.3.36
sys-apps/amdgpu_top/amdgpu_top-0.7.0.ebuild:	time@0.3.34
sys-apps/bat/bat-0.23.0-r1.ebuild:	time@0.3.14
sys-apps/bat/bat-0.24.0-r1.ebuild:	time@0.3.14
sys-apps/eza/eza-0.18.13.ebuild:	time@0.3.30
sys-apps/eza/eza-0.18.16.ebuild:	time@0.3.30
sys-apps/eza/eza-0.18.21.ebuild:	time@0.3.30
sys-apps/eza/eza-0.18.6.ebuild:	time@0.3.30
sys-apps/uutils-coreutils/uutils-coreutils-0.0.25.ebuild:	time@0.3.20
sys-apps/uutils-coreutils/uutils-coreutils-0.0.27.ebuild:	time@0.3.36
sys-apps/uutils-coreutils/uutils-coreutils-9999.ebuild:	time@0.3.36
sys-apps/uutils-findutils/uutils-findutils-0.4.2-r1.ebuild:	time@0.3.30
sys-power/wluma/wluma-4.3.0-r2.ebuild:	time@0.1.45
sys-process/below/below-0.7.0.ebuild:	time-0.3.16
sys-process/below/below-0.7.1.ebuild:	time@0.3.16
sys-process/below/below-0.8.1.ebuild:	time@0.3.16
sys-process/bottom/bottom-0.9.6.ebuild:	time-0.3.27
x11-terms/wezterm/wezterm-20240203.110809-r1.ebuild:	time@0.3.31
```
</details>

And that includes some high profile things like librsvg.

If they all do, we may want to leave it masked/unkeyworded while it gets sorted out.

File: sys-process/bottom/files/bottom-0.9.6-bump-deps.patch [hunk 1]
```diff
@@ -0,0 +1,101 @@
+From ea863b17485382259c5faef8e2f48c3b2f07ce49 Mon Sep 17 00:00:00 2001
+From: Randy Barlow <randy@electronsweatshop.com>
+Date: Thu, 25 Jul 2024 20:25:33 -0400
+Subject: [PATCH] Update time to 0.9.6
```
Comment (bowlofeggs) [inline sys-process/bottom/files/bottom-0.9.6-bump-deps.patch:4]: I added this patch in with this Rust PR since it is needed for Rust 1.80.0. I'm happy to split it out into a separate pull request if that's preferred.

**Comment by bowlofeggs** [comment]
> Do all packages with `<time-0.3.35` fail or only some of them?

Hello @ionenwks! I believe it may only affect packages that turn on the `formatting` feature. I'm unsure how many on the list you found do that.

File: sys-process/bottom/files/bottom-0.9.6-bump-deps.patch (hunk 1 above)
Comment (bowlofeggs) [reply sys-process/bottom/files/bottom-0.9.6-bump-deps.patch:4]: (I added two more bottom patches to deal with lints. Again, happy to split those to another PR if desired...)

**Comment by bowlofeggs** [comment]
One of the new features of Rust 1.80 is that it validates feature flags. I see another build failure in bottom that I may be due to this:

```
error[E0635]: unknown feature `stdsimd`
  --> /var/tmp/portage/sys-process/bottom-0.9.6-r1/work/cargo_home/gentoo/ahash-0.8.3/src/lib.rs:99:42
   |
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^
   ```

**Comment by kornelski** [comment]
@bowlofeggs `feature()` name checking isn't new. The names have always been validated.

The breakage is due to the crate opting in to use of nightly unstable compiler, and explicitly opting out of any stability guarantees to access an unfinished experimental compiler feature `stdsimd`. The `stdsimd` WIP feature had been refactored, and is no longer accepted under the previous name: https://github.com/rust-lang/rust/pull/121269 https://github.com/rust-lang/rust/commit/047ba0a280a5d23f52c717af053b3171b0f78de8

File: sys-process/bottom/files/bottom-0.9.6-bump-deps.patch (hunk 1 above)
Comment (bowlofeggs) [reply sys-process/bottom/files/bottom-0.9.6-bump-deps.patch]: I went ahead and moved bottom to its own PR. I also tested that that PR does build with this Rust 1.80 build.

See https://github.com/gentoo/gentoo/pull/37889

**Comment by bowlofeggs** [comment]
> @bowlofeggs `feature()` name checking isn't new. The names have always been validated.
> 
> The breakage is due to the crate opting in to use of nightly unstable compiler, and explicitly opting out of any stability guarantees to access an unfinished experimental compiler feature `stdsimd`. The `stdsimd` WIP feature had been refactored, and is no longer accepted under the previous name: [rust-lang/rust#121269](https://github.com/rust-lang/rust/pull/121269) [rust-lang/rust@047ba0a](https://github.com/rust-lang/rust/commit/047ba0a280a5d23f52c717af053b3171b0f78de8)

Yes! I did later look more closely and found that too. Thanks for the note!

File: sys-devel/rust-std/rust-std-1.80.0.ebuild [hunk 2]
```diff
@@ -0,0 +1,155 @@
+# Copyright 2020-2024 Gentoo Authors
+# Distributed under the terms of the GNU General Public License v2
+
+EAPI=8
+
+PYTHON_COMPAT=( python3_{9..12} )
```
Comment (arthurzam) [inline sys-devel/rust-std/rust-std-1.80.0.ebuild:6]:
```suggestion
PYTHON_COMPAT=( python3_{10..12} )
```

File: sys-devel/rust-std/rust-std-1.80.0.ebuild [hunk 3]
```diff
@@ -0,0 +1,155 @@
...
+
+inherit flag-o-matic multiprocessing python-any-r1 rust-toolchain toolchain-funcs
+
+DESCRIPTION="Rust standard library, standalone (for crossdev)"
+HOMEPAGE="https://www.rust-lang.org"
+SRC_URI="https://static.rust-lang.org/dist/rustc-${PV}-src.tar.xz"
+
```
Comment (arthurzam) [inline sys-devel/rust-std/rust-std-1.80.0.ebuild:13]: Move S= straight after SRC_URI

```suggestion
SRC_URI="https://static.rust-lang.org/dist/rustc-${PV}-src.tar.xz"
S="${WORKDIR}/${P/-std/c}-src"

```

**Comment by juippis** [comment]
I'll try to get this reviewed during weekend. I saw some build errors when testing this (will need to re-check whether it was a me-issue or rust-1.80 issue) and I want to test building Firefoxes with this rust version before acking on my part. (Anyone is free to help test/merge this earlier though!)

**Comment by chewi** [comment]
> > Do all packages with `<time-0.3.35` fail or only some of them?
> 
> Hello @ionenwks! I believe it may only affect packages that turn on the `formatting` feature. I'm unsure how many on the list you found do that.

I thought this was really worth finding out, so I wrote rather crude ~one~ three liner. I'm not sure whether it's entirely accurate, but I manually checked a few.

```
$ for EBUILD in $(cut -d: -f1 rust.txt | sort -u); do CAT=${EBUILD%%/*}; PF=${EBUILD##*/}; PF=${PF%.ebuild}; WORKDIR=/var/tmp/portage/${CAT}/${PF}/work; ebuild "${EBUILD}" clean configure &>/dev/null; S=$(sed -nr 's/^declare -x S="(.*)"/\1/p' "/var/tmp/portage/${CAT}/${PF}/temp/environment"); cd "${S}"; CARGO_HOME=${WORKDIR}/cargo_home cargo --offline tree --format "{p} {f}" --package time --depth 0 2>/dev/null | grep -F formatting | cut -d" " -f2 | awk -F. 'int(sprintf("%d%03d%03d\n", $1,$2,$3)) < 3035 { exit 1 }' || echo "${EBUILD}"; cd - >/dev/null; ebuild "${EBUILD}" clean; done

app-editors/helix/helix-24.03-r1.ebuild
app-emulation/virtiofsd/virtiofsd-1.10.0.ebuild
app-emulation/virtiofsd/virtiofsd-1.10.1.ebuild
app-emulation/virtiofsd/virtiofsd-9999.ebuild
app-misc/anki/anki-24.04.1.ebuild
app-misc/jaq/jaq-1.4.0.ebuild
app-misc/jaq/jaq-1.5.0.ebuild
app-portage/emlop/emlop-0.6.1.ebuild
app-portage/emlop/emlop-0.7.0.ebuild
app-shells/atuin/atuin-18.2.0.ebuild
app-shells/nushell/nushell-0.91.0.ebuild
app-shells/nushell/nushell-0.93.0.ebuild
app-shells/starship/starship-1.17.1.ebuild
dev-util/cargo-c/cargo-c-0.9.30.ebuild
dev-util/cargo-c/cargo-c-0.9.31.ebuild
dev-util/git-delta/git-delta-0.17.0.ebuild
dev-vcs/git-absorb/git-absorb-0.6.13-r1.ebuild
dev-vcs/stgit/stgit-2.4.6.ebuild
gnome-base/librsvg/librsvg-2.57.3.ebuild
net-misc/geckodriver/geckodriver-0.34.0.ebuild
sys-apps/amdgpu_top/amdgpu_top-0.7.0.ebuild
sys-apps/bat/bat-0.23.0-r1.ebuild
sys-apps/bat/bat-0.24.0-r1.ebuild
sys-apps/eza/eza-0.18.13.ebuild
sys-apps/eza/eza-0.18.16.ebuild
sys-apps/eza/eza-0.18.21.ebuild
sys-apps/eza/eza-0.18.6.ebuild
sys-apps/uutils-coreutils/uutils-coreutils-0.0.25.ebuild
sys-apps/uutils-findutils/uutils-findutils-0.4.2-r1.ebuild
sys-process/below/below-0.8.1.ebuild
sys-process/bottom/bottom-0.9.6.ebuild
x11-terms/wezterm/wezterm-20240203.110809-r1.ebuild
```

**Comment by chewi** [comment]
Of those, the following **do not** have this fixed in newer ebuilds:

* app-emulation/virtiofsd
* app-misc/anki
* app-portage/emlop
* dev-util/git-delta
* net-misc/geckodriver
* sys-apps/amdgpu_top
* sys-apps/bat
* sys-apps/eza
* sys-process/below
* x11-terms/wezterm

**Comment by juippis** [comment]
Note that there's geckodriver-0.35.0 pushed today in tree. Not sure if it fixes anything.

**Comment by chewi** [comment]
geckodriver-0.35.0 looks okay, it has 0.3.36.

**Comment by antecrescent** [comment]
On August 8, 2024 3:31:47 PM GMT+02:00, James Le Cuirot ***@***.***> wrote:
>Of those, the following **do not** have this fixed in newer ebuilds:
>
>* app-emulation/virtiofsd
>* app-misc/anki

https://github.com/gentoo/gentoo/pull/37222 fixes compilation with rust-1.80.0 for the version in ::gentoo and for the new addition.
The two first Rust-related commits could be merged independently of the rest.

**Comment by hhoffstaette** [comment]
You've probably seen this already but [1.80.1](https://blog.rust-lang.org/2024/08/08/Rust-1.80.1.html) is out and the FP comparison stuff seems to be serious enough to skip 1.80.0.

**Comment by bowlofeggs** [comment]
> You've probably seen this already but [1.80.1](https://blog.rust-lang.org/2024/08/08/Rust-1.80.1.html) is out and the FP comparison stuff seems to be serious enough to skip 1.80.0.

Thanks! I added a task on the OP for this.

**Comment by bowlofeggs** [comment]
> You've probably seen this already but [1.80.1](https://blog.rust-lang.org/2024/08/08/Rust-1.80.1.html) is out and the FP comparison stuff seems to be serious enough to skip 1.80.0.

I've pushed it to 1.80.1 in https://github.com/gentoo/gentoo/compare/361ec0d0f2c86d0fc8a49db120373544873c9471..9a19c8af177b51c51588d1de8ab7feea75979034

File: sys-devel/rust-std/rust-std-1.80.0.ebuild (hunk 2 above)
Comment (bowlofeggs) [reply sys-devel/rust-std/rust-std-1.80.0.ebuild]: https://github.com/gentoo/gentoo/compare/9a19c8af177b51c51588d1de8ab7feea75979034..1f47d0e041949cdcac80a3dbd66cf7d0b25fc0cc

File: sys-devel/rust-std/rust-std-1.80.0.ebuild (hunk 3 above)
Comment (bowlofeggs) [reply sys-devel/rust-std/rust-std-1.80.0.ebuild]: https://github.com/gentoo/gentoo/compare/1f47d0e041949cdcac80a3dbd66cf7d0b25fc0cc..b28586e5ea267362fef858f215b35f63fa9d113d

**Review by juippis — APPROVED** [review]
So yeah, few things: It seems mostly okay. I did get:
```
 * QA Notice: Symbolic link /usr/lib/rust/libexec-1.80.1 points to /usr/lib/rust/1.80.1/libexec which does not exist.
>>> /usr/lib/rust/libexec-1.80.1 -> 1.80.1/libexec
```
on **dev-lang/rust-1.80.1**. 

rust-std-1.80.1 I can't test at all since:
```
 * ERROR: sys-devel/rust-std-1.80.1::gentoo failed (pretend phase):
 *   rust-std should only be used for cross
 *
 * Call stack:
 *                ebuild.sh, line 136:  Called pkg_pretend
 *   rust-std-1.80.1.ebuild, line  59:  Called die
 * The specific snippet of code:
 *      is_cross || die "${PN} should only be used for cross"
```
which is probably fine.

I could compile firefox-129.0 with this rust so I'm happy with it, although that soname error should probably be looked at.

**Comment by juippis** [comment]
Will merge after ~12 hours unless someone objects.

**Review by arthurzam — APPROVED** [review]
Worked on some random arches I've tested it for, and in the middle of bootstrapping it (no action needed in this PR from me, just giving some extra good news).

We should also request a tinderbox run on all rust dependencies, just so we can file bugs for failure to build with rust 1.80. Ideally we should also create a tracker for those.

**Comment by hhoffstaette** [comment]
> Do all packages with `<time-0.3.35` fail or only some of them? From quick grep this is all the packages using time, and many still don't have a `>=0.3.35` version with the linked fix (this wouldn't catch vendored crates like starship's too).

Should be every dependency on time<0.3.35. I encountered the same problem with rustic in my overlay and instead of updating the dependency, I found it much easier to just smash a patch into time, see [here](https://github.com/hhoffstaette/portage/commit/4f6c5245e1ae01ddca5ee53e1f7bf920f8eb3aea).
Feel free to borrow.

**Comment by thesamesam** [comment]
> Should be every dependency on time<0.3.35.

This was already answered way above by Chewi in https://github.com/gentoo/gentoo/pull/37727#issuecomment-2275820344.
