### PR TITLE
net-dns/dnssec-validator: bump to version 2.2.3

### PR DESCRIPTION
**Pull request by ConiKost**
The old dnsval package seems to be removed by upstream,
as it has been integrated into the dnssec-tools package.
This version also adds support for openssl-1.1.

Closes: https://bugs.gentoo.org/641552
Closes: https://bugs.gentoo.org/672494
Package-Manager: Portage-2.3.52, Repoman-2.3.12
Signed-off-by: Conrad Kostecki <conrad@kostecki.com>

### CODE REVIEW

**Comment by juippis** [comment]
https://packages.gentoo.org/packages/net-dns/dnssec-tools - latest is 2.2.3 too. 

Maybe this needs to be last-rited, and the current dnssec-tools-2.2.3 patched with openssl thing? It has no maintainer, so you should be able to take it with ease.

**Comment by ConiKost** [comment]
> Maybe this needs to be last-rited, and the current dnssec-tools-2.2.3 patched with openssl thing?

Hm? dnssec-tools-2.2.3 do compile fine with openssl-1.1?
FWICS, it has been splited in the past into `dnsval-2.2.tar.gz`, which got in the meantime removed by upstream and integrated into the dnssec-tools. That eBuild says: `DNSSEC Validator has been split into net-dns/dnssec-validator`. Not sure, if it should be reintegrated?

**Comment by juippis** [comment]
>Hm? dnssec-tools-2.2.3 do compile fine with openssl-1.1?

Ok, sorry, thought you added a patch for that.

>That eBuild says: DNSSEC Validator has been split into net-dns/dnssec-validator

Guess someone didn't read changelog throughly when bumping it, then, since you say this package has now been merged into dnssec-tools ;)

>Not sure, if it should be reintegrated?

I don't know, but I do know that your SRC_URI and Manifest sha hash is identical to dnssec-tools-2.2.3 that's currently in the tree. Try to install these packages simultaneously.

**Comment by ConiKost** [comment]
> Guess someone didn't read changelog throughly when bumping it, then, since you say this package has now been merged into dnssec-tools ;)

I don't think so, as the other eBuild explicitly says `--with-validator`.

> I don't know, but I do know that your SRC_URI and Manifest sha hash is identical to dnssec-tools-2.2.3 that's currently in the tree.

Yes, I am aware of this.

> EDIT: Maybe add USE flag for dnssec-tools to include validator, IF it doesnt ship it unconditionally?
That's a good question. Note: The validator is a complete own subproject with it's own build files, so I am not sure, if it's a good idea. @Polynomial-C: Since you bumped `dnssec-tools` to 2.2.3, what do you think?

**Comment by robbat2** [comment]
@ConiKost  this fails to compile on `dev-libs/openssl-1.0.2q`.

```
libtool: warning: '-version-info' is ignored for programs
libtool: link: x86_64-pc-linux-gnu-gcc -march=native -O2 -pipe -Ulinux -Dlinux=linux -Ulinux -Dlinux=linux -DLIBVAL_CONFIGURED=1 -I../include -I.. -I../libsres -I../libval -D_GNU_SOURCE -o .libs/dt-validate validator_driver.o validator_selftest.o -Wl,--hash-style=gnu -Wl,-O1  -Wl,--as-needed ../libval/.libs/libval-threads.so /dev/shm/portage/net-dns/dnssec-validator-2.2.3/work/DNSSEC-Tools-dnssec-tools-2.2.3/dnssec-tools/validator/libsres/.libs/libsres.so ../libsres/.libs/libsres.so -lnsl -lssl -lcrypto -lpthread -Wl,-rpath -Wl,/usr/lib64
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libval/.libs/libval-threads.so: undefined reference to `DSA_set0_pqg'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libval/.libs/libval-threads.so: undefined reference to `ECDSA_SIG_set0'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /dev/shm/portage/net-dns/dnssec-validator-2.2.3/work/DNSSEC-Tools-dnssec-tools-2.2.3/dnssec-tools/validator/libsres/.libs/libsres.so: undefined reference to `HMAC_CTX_new'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libval/.libs/libval-threads.so: undefined reference to `EVP_MD_CTX_free'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libval/.libs/libval-threads.so: undefined reference to `DSA_set0_key'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libval/.libs/libval-threads.so: undefined reference to `RSA_get0_key'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libval/.libs/libval-threads.so: undefined reference to `EVP_MD_CTX_new'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libval/.libs/libval-threads.so: undefined reference to `RSA_set0_key'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /dev/shm/portage/net-dns/dnssec-validator-2.2.3/work/DNSSEC-Tools-dnssec-tools-2.2.3/dnssec-tools/validator/libsres/.libs/libsres.so: undefined reference to `HMAC_CTX_free'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:131: dt-validate] Error 1
make[1]: Leaving directory '/dev/shm/portage/net-dns/dnssec-validator-2.2.3/work/DNSSEC-Tools-dnssec-tools-2.2.3/dnssec-tools/validator/apps'
```

**Comment by ConiKost** [comment]
@robbat2 Thank you very much. I've tried to fix this, but ended giving up, since I've no clue how to fix this probably. I've added for now min openssl-1.1 as dep.

File: net-dns/dnssec-validator/dnssec-validator-2.2.3.ebuild [hunk 1]
```diff
@@ -0,0 +1,63 @@
+# Copyright 1999-2019 Gentoo Authors
+# Distributed under the terms of the GNU General Public License v2
+
+EAPI=7
+
+inherit autotools
+
+MY_PN="dnssec-tools"
```
Comment (mgorny) [inline net-dns/dnssec-validator/dnssec-validator-2.2.3.ebuild]: This is thoroughly confusing. Kill those vars, as they are used unpredictably anyway.

File: net-dns/dnssec-validator/dnssec-validator-2.2.3.ebuild [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+DESCRIPTION="Tools to ease the validation of DNSSEC related technologies"
+HOMEPAGE="https://www.dnssec-tools.org/"
+SRC_URI="https://github.com/${MY_PN2}/${MY_PN2}/archive/${MY_P}.tar.gz"
+
+KEYWORDS="~amd64 ~arm ~x86"
+LICENSE="BSD"
+SLOT="0"
+IUSE="dlv +ipv6 +nsec3 +threads"
+
+RDEPEND=">dev-libs/openssl-1.0.2:0"
```
Comment (mgorny) [inline net-dns/dnssec-validator/dnssec-validator-2.2.3.ebuild]: `>=`?

File: net-dns/dnssec-validator/files/dnssec-validator-2.2.3-ldflags.patch [hunk 3]
```diff
@@ -0,0 +1,33 @@
+--- a/libsres/Makefile.in	2018-08-30 00:25:30.000000000 +0200
```
Comment (mgorny) [inline net-dns/dnssec-validator/files/dnssec-validator-2.2.3-ldflags.patch]: Is this submitted upstream? Please add a link to the top.

File: net-dns/dnssec-validator/dnssec-validator-2.2.3.ebuild (hunk 1 above)
Comment (ConiKost) [reply net-dns/dnssec-validator/dnssec-validator-2.2.3.ebuild]: Yes. It sould be maybe questioned, if this package should not be killed entierly and integrated into ```net-dns/dnssec-tools```, since it included in the source of it. But no one replied to me, when I asked maintainer :-) What do you think in this case? It was splitted in past, but in current source it's included there.

File: net-dns/dnssec-validator/dnssec-validator-2.2.3.ebuild (hunk 2 above)
Comment (ConiKost) [reply net-dns/dnssec-validator/dnssec-validator-2.2.3.ebuild]: See @robbat2 comment. It won't compile on ```openssl-1.0.2``` series.

File: net-dns/dnssec-validator/files/dnssec-validator-2.2.3-ldflags.patch (hunk 3 above)
Comment (ConiKost) [reply net-dns/dnssec-validator/files/dnssec-validator-2.2.3-ldflags.patch]: Nope, I patched this by myself. Should I report upstream?

File: net-dns/dnssec-validator/dnssec-validator-2.2.3.ebuild (hunk 2 above)
Comment (mgorny) [reply net-dns/dnssec-validator/dnssec-validator-2.2.3.ebuild]: Then you want `>=1.1.0`

File: net-dns/dnssec-validator/files/dnssec-validator-2.2.3-ldflags.patch (hunk 3 above)
Comment (mgorny) [reply net-dns/dnssec-validator/files/dnssec-validator-2.2.3-ldflags.patch]: Yes.

File: net-dns/dnssec-validator/dnssec-validator-2.2.3.ebuild (hunk 1 above)
Comment (mgorny) [reply net-dns/dnssec-validator/dnssec-validator-2.2.3.ebuild]: Start by removing the extra vars.

Comment (ConiKost) [reply net-dns/dnssec-validator/dnssec-validator-2.2.3.ebuild]: Already done.

File: net-dns/dnssec-validator/files/dnssec-validator-2.2.3-ldflags.patch (hunk 3 above)
Comment (ConiKost) [reply net-dns/dnssec-validator/files/dnssec-validator-2.2.3-ldflags.patch]: Done.

File: net-dns/dnssec-validator/dnssec-validator-2.2.3.ebuild (hunk 2 above)
Comment (ConiKost) [reply net-dns/dnssec-validator/dnssec-validator-2.2.3.ebuild]: Done.
