### PR TITLE
net-libs/nodejs: add bundled-openssl useflag

### PR DESCRIPTION
**Pull request by soredake**

### CODE REVIEW

**Comment by mgorny** [comment]
You really need a very good reason to get this through. OpenSSL is a frequent recipient of CVEs, so bundling an old version is a guaranteed security issue.

**Comment by soredake** [comment]
I switched to my system libressl, and i need nodejs installed, it's my reason.

**Comment by gktrk** [comment]
@gentoo/proxy-maint @patricklauer

**Comment by patricklauer** [comment]
CAN YOU PLEASE STOP SPAMMING ME.

Thanks you for your voluntary cooperation with this mandatory policy.

**Comment by soredake** [comment]
@mgorny i see void linux using libressl with node without patches now (old patch for old versions is here https://github.com/voidlinux/void-packages/pull/2574/commits/00b70d7d42308fb969827fea6f0840d7263b38e4), https://github.com/voidlinux/void-packages/blob/master/srcpkgs/nodejs/template#L8, but i have no luck with this:
```
../src/node_crypto.cc: In instantiation of ‘static void node::crypto::SSLWrap<Base>::CertCbDone(const v8::FunctionCallbackInfo<v8::Value>&) [with Base = node::crypto::Connection]’:
../src/node_crypto.cc:1216:3:   required from ‘static void node::crypto::SSLWrap<Base>::AddMethods(node::Environment*, v8::Local<v8::FunctionTemplate>) [with Base = node::crypto::Connection]’
../src/node_crypto.cc:2647:24:   required from here
../src/node_crypto.cc:2380:42: error: ‘SSL_CTX_get0_certificate’ was not declared in this scope
     X509* x509 = SSL_CTX_get0_certificate(sc->ctx_);
                                          ^
../src/node_crypto.cc:2381:45: error: ‘SSL_CTX_get0_privatekey’ was not declared in this scope
     EVP_PKEY* pkey = SSL_CTX_get0_privatekey(sc->ctx_);
                                             ^
../src/node_crypto.cc:2384:34: error: ‘SSL_CTX_get0_chain_certs’ was not declared in this scope
     rv = SSL_CTX_get0_chain_certs(sc->ctx_, &chain);
                                  ^
../src/node_crypto.cc:2390:26: error: ‘SSL_set1_chain’ was not declared in this scope
       rv = SSL_set1_chain(w->ssl_, chain);
                          ^
../src/node_crypto.cc: In instantiation of ‘static void node::crypto::SSLWrap<Base>::GetEphemeralKeyInfo(const v8::FunctionCallbackInfo<v8::Value>&) [with Base = node::crypto::Connection]’:
../src/node_crypto.cc:1223:3:   required from ‘static void node::crypto::SSLWrap<Base>::AddMethods(node::Environment*, v8::Local<v8::FunctionTemplate>) [with Base = node::crypto::Connection]’
../src/node_crypto.cc:2647:24:   required from here
../src/node_crypto.cc:1867:29: error: ‘SSL_get_server_tmp_key’ was not declared in this scope
   if (SSL_get_server_tmp_key(w->ssl_, &key)) {
                             ^
../src/node_crypto.cc: In instantiation of ‘int node::crypto::SSLWrap<Base>::SetCACerts(node::crypto::SecureContext*) [with Base = node::crypto::Connection]’:
../src/node_crypto.cc:2448:13:   required from ‘void node::crypto::SSLWrap<Base>::SetSNIContext(node::crypto::SecureContext*) [with Base = node::crypto::Connection]’
../src/node_crypto.cc:2781:31:   required from here
../src/node_crypto.cc:2454:39: error: ‘SSL_set1_verify_cert_store’ was not declared in this scope
   int err = SSL_set1_verify_cert_store(ssl_, SSL_CTX_get_cert_store(sc->ctx_));
                                       ^
```

**Comment by llacroix** [comment]
Could make sense to make a new patch, it's been 2 years and the old patch isn't working with more recent version such as >=7.2.x
