### PR TITLE
improve antlr usage for mysql-workbench

### PR DESCRIPTION
**Pull request by efferre79**
mysql-workbench is currently using an embedded version of antlr-tool. First of all I added the missing antlr version to use system version of the tool. I had to increase the minimum JDK version due to sources compatibility. Then I patched mysql-workbench to support the system antlr tool.

Moreover when running antlr-tool we must be sure that the system JVM is able to run the bytecode of the classes. There is no automatic mechanism to track this from the dependencies so I have enforced a check at pkg_setup() phase, the fixing is let to the user who has to manually switch the current JVM. This avoids building failure and bug notification

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by vaukai** [comment]
`dev-java/antlr-tool`, `dev-java/antlr-runtime` and `dev-java/antlr` are three different packages and should not get bumped withing the same commit.

**Comment by efferre79** [comment]
> `dev-java/antlr-tool`, `dev-java/antlr-runtime` and `dev-java/antlr` are three different packages and should not get bumped withing the same commit.

I was thinking to have an atomic commit because they are all related, I will make separate commits then

How should I solve the QA complain about java-pkg_ensure-vm-version-ge()?

**Comment by vaukai** [comment]
> How should I solve the QA complain about java-pkg_ensure-vm-version-ge()?

I am not aware of such ...

**Comment by efferre79** [comment]
> > How should I solve the QA complain about java-pkg_ensure-vm-version-ge()?
> 
> I am not aware of such ...

It's not used anywhere in portage, I would propose to promote that function to be not internal by removing the tag INTERNAL from the function header

**Comment by vaukai** [comment]
> > > How should I solve the QA complain about java-pkg_ensure-vm-version-ge()?
> > 
> > 
> > I am not aware of such ...
> 
> It's not used anywhere in portage, I would propose to promote that function to be not internal by removing the tag INTERNAL from the function header

If you mean these [InternalEclassUsage](https://qa-reports.gentoo.org/output/gentoo-ci/9ec94d3/output.html#dev-db/mysql-workbench) messages and those lines aren't used in the ebuilds, where do the complanits come from?

**Comment by efferre79** [comment]
> > > > How should I solve the QA complain about java-pkg_ensure-vm-version-ge()?
> > > 
> > > 
> > > I am not aware of such ...
> > 
> > 
> > It's not used anywhere in portage, I would propose to promote that function to be not internal by removing the tag INTERNAL from the function header
> 
> If you mean these [InternalEclassUsage](https://qa-reports.gentoo.org/output/gentoo-ci/9ec94d3/output.html#dev-db/mysql-workbench) messages and those lines aren't used in the ebuilds, where do the complanits come from?

I assumed that those INTERNAL tags in the eclass are used by pkgcheck for the QA checks. I tried deleting that line in the eclass and executed locally pkgcheck, I see that it is refreshing the cache of the modified eclass but the outcome is still the same. Anyway the eclass documentation page in the devmanual confirms that the tags are used by pkgcheck.

**Comment by efferre79** [comment]
Besides the QA InternalEclassUsage reports than cannot be solved without changing also the java-utils-2.eclass, I consider this PR ready to be merged

**Comment by vaukai** [comment]
imho, without dekeywording `~x86` there would be no way.

And, even with `USE=X emerge -1a =mysql-wotkbench-8.0.41::gentoo` I cannot reproduce https://bugs.gentoo.org/933844.

**Comment by efferre79** [comment]
> imho, without dekeywording `~x86` there would be no way.

Please be more clear about what you mean, I didn't add or remove new keywords

> And, even with `USE=X emerge -1a =mysql-wotkbench-8.0.41::gentoo` I cannot reproduce https://bugs.gentoo.org/933844.

Please tell me what `java-config -f` reports to you

**Comment by efferre79** [comment]
The situation is pretty clear by reading carefully the related bug. Basically in the ebuild there is a build dependency on `>=virtual/jre-11` but actually I don't see any enforcing on which JVM is effectively executed at build time. If there are multiple JVM installed in the system, the one selected as active is used during `src_compile()` to call antlr-tool. So it _might_ happen you don't face the problem in the bug report as you experienced. The problem is that the current ebuild doesn't call `java-pkg_init()`. After skimming through the eclass code I found another source of problems, the function `java-pkg_needs-vm()` considers only JDK and not JRE as possible JVM, so even calling `java-pkg_init()` won't solve the issue.

On my freshly installed system I had selected openjdk-bin-8 which doesn't support the bytecode of binary antlr used in the currently available mysql-workbench version in portage. So the eclass should be fixed and then only calling `java-pkg_init()` should solve the problem. I'll prepare another PR for that issue. IMHO the issue will return next time when the binary anltr changes bytecode and needs e.g. jvm version 17 minimum. It is clearly a duty of the ebuild developer to keep the DEPEND string correct but with the current implementation in this PR I made a step further. Ideally with the approach of the current PR it is possible to improve the current java eclass by checking the bytecode of classes in [R]DEPEND well in advance of compilation time. In that way it is possible to avoid bug reports similar to the one related to this PR.

**Comment by vaukai** [comment]
> > imho, without dekeywording `~x86` there would be no way.
> 
> Please be more clear about what you mean, I didn't add or remove new keywords

Sorry for not being clear enough. I was referring to these lines in the [ci message](https://qa-reports.gentoo.org/output/gentoo-ci/f88560c/output.html#dev-db/mysql-workbench):
```
NonsolvableDepsInStable	nonsolvable depset(depend) keyword(~x86) stable profile (default/linux/x86/23.0/i686) (15 total): solutions: [ >=dev-java/antlr-tool-4.11.1:4 ]
NonsolvableDepsInStable	nonsolvable depset(depend) keyword(~x86) stable profile (default/linux/x86/23.0/i686) (15 total): solutions: [ >=dev-java/antlr-tool-4.11.1:4 ]
NonsolvableDepsInStable	nonsolvable depset(depend) keyword(~x86) stable profile (default/linux/x86/23.0/i686) (15 total): solutions: [ >=dev-java/antlr-tool-4.11.1:4 ]
```
dekeywording those mysql-workbench versions for `~x86` should solve it.

File: dev-db/mysql-workbench/mysql-workbench-8.0.38-r1.ebuild [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+	sed -i -e 's/-O0 -g3//' ext/scintilla/gtk/CMakeLists.txt || die
+	## And avoid -Werror
+	sed -i -e 's/-Werror//' CMakeLists.txt || die
+	## Fix doc install directory
+	sed -i -e "/WB_INSTALL_DOC_DIR/ s/mysql-workbench/${P}/ ; /WB_INSTALL_DOC_DIR/ s/-community//" CMakeLists.txt || die
+
+	## package is very fragile...
+	strip-flags
+
+	cmake_src_prepare
```
[the remark this answers is not in the document]
Comment (efferre79) [reply dev-db/mysql-workbench/mysql-workbench-8.0.38-r1.ebuild:97]: there are a couple of files but not used by the build system (they are used to regenerate locally the syntax parser, used only by developers working on the code)

**Comment by efferre79** [comment]
> > > imho, without dekeywording `~x86` there would be no way.
> > 
> > 
> > Please be more clear about what you mean, I didn't add or remove new keywords
> 
> Sorry for not being clear enough. I was referring to these lines in the [ci message](https://qa-reports.gentoo.org/output/gentoo-ci/f88560c/output.html#dev-db/mysql-workbench):
> 
> ```
> NonsolvableDepsInStable	nonsolvable depset(depend) keyword(~x86) stable profile (default/linux/x86/23.0/i686) (15 total): solutions: [ >=dev-java/antlr-tool-4.11.1:4 ]
> NonsolvableDepsInStable	nonsolvable depset(depend) keyword(~x86) stable profile (default/linux/x86/23.0/i686) (15 total): solutions: [ >=dev-java/antlr-tool-4.11.1:4 ]
> NonsolvableDepsInStable	nonsolvable depset(depend) keyword(~x86) stable profile (default/linux/x86/23.0/i686) (15 total): solutions: [ >=dev-java/antlr-tool-4.11.1:4 ]
> ```
> 
> dekeywording those mysql-workbench versions for `~x86` should solve it.

this must be decided by the mysql-workbench maintainer

File: dev-db/mysql-workbench/mysql-workbench-8.0.38-r1.ebuild (hunk 1 above)
[the remark this answers is not in the document]
Comment (vaukai) [reply dev-db/mysql-workbench/mysql-workbench-8.0.38-r1.ebuild:97]: If so, adding `java-pkg-2_src_prepare` and `java-pkg_clean` should not break the build, right?

**Comment by vaukai** [comment]
> this must be decided by the mysql-workbench maintainer

We always have to do that when adding new dependencies which aren't yet fully keyworded. Maybe followed by a re-keywording request.

**Comment by efferre79** [comment]
> > this must be decided by the mysql-workbench maintainer
> 
> We always have to do that when adding new dependencies which aren't yet fully keyworded. Maybe followed by a re-keywording request.

instead of dekeywording mysql-workbench which would require later a new rekeywording for it and antlr, what about splitting this PR by first adding antlr, new keywording request for it and finally applying the rest of this PR? Is x86 still really supported and needed? For that reason I was asking if the mysql-maintainer thinks that we can directly drop x86.

File: dev-db/mysql-workbench/mysql-workbench-8.0.38-r1.ebuild (hunk 1 above)
[the remark this answers is not in the document]
Comment (efferre79) [reply dev-db/mysql-workbench/mysql-workbench-8.0.38-r1.ebuild:97]: that's correct, I am against adding those calls because mysql-workbench is not really a java-package but a Java consumer and we are not building any java class. But if that is the policy when inheriting java-pkg-2 I can add those calls.

**Comment by vaukai** [comment]
> > > this must be decided by the mysql-workbench maintainer
> > 
> > 
> > We always have to do that when adding new dependencies which aren't yet fully keyworded. Maybe followed by a re-keywording request.
> 
> instead of dekeywording mysql-workbench which would require later a new rekeywording for it and antlr, what about splitting this PR by first adding antlr, new keywording request for it [...]

See https://public-inbox.gentoo.org/gentoo-dev/8b5afc32-a4ec-42a3-a54e-7d01ac8596ad@gentoo.org/ 
and https://github.com/gentoo/gentoo/commit/b60a91221f

**Comment by efferre79** [comment]
> > instead of dekeywording mysql-workbench which would require later a new rekeywording for it and antlr, what about splitting this PR by first adding antlr, new keywording request for it [...]
> 
> See https://public-inbox.gentoo.org/gentoo-dev/8b5afc32-a4ec-42a3-a54e-7d01ac8596ad@gentoo.org/ and [b60a91221f](https://github.com/gentoo/gentoo/commit/b60a91221f)

Thanks for pointing out to that. So this means that dekeywording mysql-workbench should be done for all ebuilds, which means that 8.0.4[01] should be 8.0.4[01]-r1 right?

So if we want to remove the antlr binary dep from mysql-workbench than we need the new version of antlr* packages commited in portage and dekeywording mysql-workbench with the removal of x86 support.

**Comment by vaukai** [comment]
> > > instead of dekeywording mysql-workbench which would require later a new rekeywording for it and antlr, what about splitting this PR by first adding antlr, new keywording request for it [...]
> > 
> > 
> > See https://public-inbox.gentoo.org/gentoo-dev/8b5afc32-a4ec-42a3-a54e-7d01ac8596ad@gentoo.org/ and [b60a91221f](https://github.com/gentoo/gentoo/commit/b60a91221f)
> 
> Thanks for pointing out to that. So this means that dekeywording mysql-workbench should be done for all ebuilds, which means that 8.0.4[01] should be 8.0.4[01]-r1 right?

Looking at all those dekeywording commits in ::gentoo, e.g. commit #a18a91ca81ae9e94cb868e5485e6dd0d43bf1ffd I do not see a revision bump ...
> 
> So if we want to remove the antlr binary dep from mysql-workbench than we need the new version of antlr* packages commited in portage and dekeywording mysql-workbench with the removal of x86 support.

And the dekeywording request is usually done within the pull request. Look at my [joda-convert, joda-time and snakeyaml](https://github.com/gentoo/gentoo/compare/master...vaukai:protobuf-java) commits after packaging threetenbp as a new compile dependency.

File: dev-db/mysql-workbench/mysql-workbench-8.0.41.ebuild [hunk 2]
```diff
@@ -62,16 +58,28 @@ RDEPEND="${CDEPEND}
 		>=sys-apps/net-tools-1.60_p20120127084908"
 
 DEPEND="${CDEPEND}
+		>=dev-java/antlr-tool-4.11.1:4
+		>=dev-cpp/antlr-cpp-4.11.1:4
 		dev-lang/swig
-		>=virtual/jre-11
+		>=virtual/jre-11:11
```
[the remark this answers is not in the document]
Comment (efferre79) [reply dev-db/mysql-workbench/mysql-workbench-8.0.41.ebuild]: thanks, fixed. For all the unstable ebuilds I suppose a revdump is not needed (like for the dekeywording), 8.0.38-r1 is anyway new and for that I revdumped

[the remark this answers is not in the document]
Comment (vaukai) [reply dev-db/mysql-workbench/mysql-workbench-8.0.41.ebuild]: Just for fun, I've pram'ed this pr and had a closer look.
Turns out it still supports target `1.8` and there is no reason at all for not keeping `>=virtual/jdk-1.8:*` and `>=virtual/jre-1.8:*` for all `antlr*-4.11*`. 

Do the tests all pass for you???

[the remark this answers is not in the document]
Comment (efferre79) [reply dev-db/mysql-workbench/mysql-workbench-8.0.41.ebuild]: I have raised the minimum JDK to version 11 because antlr-tool fails to build with 1.8:

```
javac -source 1.8 -target 1.8 -d target/classes -encoding UTF-8 -classpath /usr/share/antlr-runtime-4/lib/antlr-runtime.jar:/usr/share/antlr-runtime-3.5/lib/antlr-runtime.jar:/usr/share/jakarta-json-api-1/lib/jakarta-json-api.jar:/usr/share/icu4j/lib/icu4j.jar:/usr/share/icu4j/lib/icu4j-charset.jar:/usr/share/icu4j/lib/icu4j-localespi.jar:/usr/share/stringtemplate-4/lib/stringtemplate.jar:/usr/share/treelayout/lib/treelayout.jar:/usr/share/stringtemplate/lib/stringtemplate.jar:/usr/share/antlr/lib/antlr.jar @sources.lst
tool/src/org/antlr/v4/gui/Interpreter.java:140: error: cannot find symbol
			String grammarContent = Files.readString(Path.of(grammarFileName));
			                                             ^
  symbol:   method of(String)
  location: interface Path

```                                             ^

[the remark this answers is not in the document]
Comment (efferre79) [reply dev-db/mysql-workbench/mysql-workbench-8.0.41.ebuild]: I cannot understand how. [Path.of](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html) is not available with 1.8

[the remark this answers is not in the document]
Comment (vaukai) [reply dev-db/mysql-workbench/mysql-workbench-8.0.41.ebuild]: Sorry if causing confusion.  My last comments since https://github.com/gentoo/gentoo/pull/41056#discussion_r1999065492 refer only to the `antlr-*` part.

[the remark this answers is not in the document]
Comment (efferre79) [reply dev-db/mysql-workbench/mysql-workbench-8.0.41.ebuild]: > Do the tests all pass for you???

It's actually impossible to run the tests for antlr-runtime and antlr-tool because many required deps are not present in portage. It is probably better to restrict them?

[the remark this answers is not in the document]
Comment (vaukai) [reply dev-db/mysql-workbench/mysql-workbench-8.0.41.ebuild]: > > Do the tests all pass for you???
> 
> It's actually impossible to run the tests for antlr-runtime and antlr-tool because many required deps are not present in portage. It is probably better to restrict them?

Missing test dependencies could be handled (see SRC_URI of `dev-java/testng-6.11-r1`) or compare the handling of truth in an [older version](https://packages.gentoo.org/packages/dev-java/protobuf-java) and [my latest version](https://github.com/gentoo/gentoo/compare/master...vaukai:protobuf-java) of `dev-java/protobuf-java`.

**Comment by efferre79** [comment]
> @efferre79 Just a question: Isn't `antlr` used by `mysql-workbench` mainly/only in a script for generating some `*.cpp` stuff? If so, wouldn't it be possible to use [dev-cpp/antlr-cpp](https://packages.gentoo.org/packages/dev-cpp/antlr-cpp) instead?

As already pointed out previously, I confirm that mysql-workbench uses only the antlr tool to generate the parser code. That is the reason is requires only JRE. antlr-cpp are the cpp bindings, i.e. only a bunch of headers and shared library. I am **definitely** not going to change the upstream build system besides what is needed to use system antlr-tool.

File: dev-db/mysql-workbench/mysql-workbench-8.0.41.ebuild (hunk 2 above)
[the remark this answers is not in the document]
Comment (efferre79) [reply dev-db/mysql-workbench/mysql-workbench-8.0.41.ebuild]: Maybe it is better thinking what is the aim here. Here we are requiring antlr-* **to remove** a binary dependency from mysql-workbench. To support tests with antlr* you are asking **to include** other binary dependencies, IMHO this is no sense. I would suggest to add `RESTRICT=test` where needed for antlr* so that we can go on with this PR otherwise we are going out of scope, we cannot solve everything is a single step. In this PR we are already trying to solve two problems, one is the real [bug](https://bugs.gentoo.org/933844) and the second is to remove the binary dependency.

If you are against adding antlr*4.11 then we can solve only the first of the two issues with the [other PR](https://github.com/gentoo/gentoo/pull/41084) I opened by modifing the java-utils-2.eclass (i.e. JRE detection as valid JVM).

[the remark this answers is not in the document]
Comment (vaukai) [reply dev-db/mysql-workbench/mysql-workbench-8.0.41.ebuild]: > Maybe it is better thinking what is the aim here. Here we are requiring antlr-* **to remove** a binary dependency from mysql-workbench. To support tests with antlr* you are asking **to include** other binary dependencies, IMHO this is no sense. I would suggest to add `RESTRICT=test` where needed for antlr* so that we can go on with this PR otherwise we are going out of scope, we cannot solve everything is a single step. In this PR we are already trying to solve two problems, one is the real [bug](https://bugs.gentoo.org/933844) and the second is to remove the binary dependency.
> 
> If you are against adding antlr*4.11 then we can solve only the first of the two issues with the [other PR](https://github.com/gentoo/gentoo/pull/41084) I opened by modifing the java-utils-2.eclass (i.e. JRE detection as valid JVM).

Don't take me wrong, I am not against adding new versions or new packages but in this case where just a single package is affected, the new versions (which are not even the latest) plus eclass changes just for avoiding to have `virtual/jdk` in DEPEND appear as a huge overkill. Please compare https://github.com/gentoo/gentoo/pull/41174

[the remark this answers is not in the document]
Comment (efferre79) [reply dev-db/mysql-workbench/mysql-workbench-8.0.41.ebuild]: It's not the fact that only one package is affected but that you are only implementing a workaround for an evident bug in the eclass. BTW the suggested eclass change in the other PR is quite simple and basic, have you looked at it? By depending on `virtual/jdk` when only the runtime is needed is the real overkill. And beware that `virtual/jre` already pulls  `virtual/jdk` as a possible candidate to satisfy the dependency. Which is then the aim of having `virtual/jre` in portage when `virtual/jdk` must used? Moreover I don't think mysql-workbench needs java at runtime so filling also RDEPEND is not correct.

As I have opened many PR regarding java stuff, but none has been considered so far, I deduce those contributions are not useful. We all know that java support in portage has large margin of improvements, I thought I could have given some help, but now I fell I have only wasted a lot of time so I'll stop contributing to Gentoo on that side.

**Comment by vaukai** [comment]
There are newer versions `4.13.2` of [antlr](https://packages.gentoo.org/packages/dev-java/antlr),, [antlr-runtime](https://packages.gentoo.org/packages/dev-java/antlr-runtime) and [antlr-tool](https://packages.gentoo.org/packages/dev-java/antlr-tool) in the tree. So, could the first three commits be dropped? Or are still needed?

File: dev-db/mysql-workbench/mysql-workbench-8.0.41.ebuild (hunk 2 above)
[the remark this answers is not in the document]
Comment (thesamesam) [reply dev-db/mysql-workbench/mysql-workbench-8.0.41.ebuild]: >  I fell I have only wasted a lot of time so I'll stop contributing to Gentoo on that side.

I'm sorry about that. I am happy to help unstick things if you are willing to give another go. Just ping me please.

**Comment by arthurzam** [comment]
Closed as stale, unresponsive author. Newer versions where merged and handled.
