### PR TITLE
sys-boot/{refind,udk}: Bugs 588440, 566930, 563226 and 582716

### PR DESCRIPTION
**Pull request by sveyret**
Here is the PR containing the patchs uploaded to Bugzilla for the indicated bugs.
@wraeth

### CODE REVIEW

**Comment by Amynka** [comment]
@gentoo/proxy-maint

File: sys-boot/refind/refind-0.10.2.ebuild [hunk 1]
```diff
@@ -39,19 +40,78 @@ pkg_setup() {
 	fi
 }
 
+src_prepare() {
+	eapply_user
```
Comment (SoapGentoo) [inline sys-boot/refind/refind-0.10.2.ebuild]: prefer `default` here

File: sys-boot/refind/refind-0.10.2.ebuild [hunk 2]
```diff
@@ -39,19 +40,78 @@ pkg_setup() {
...
+	for f in "${S}"/*/Make.tiano "${S}"/Make.common; do
```
Comment (SoapGentoo) [inline sys-boot/refind/refind-0.10.2.ebuild]: declare `f` local before to keep environmental pollution to a minimum

File: sys-boot/refind/refind-0.10.2.ebuild [hunk 3]
```diff
@@ -39,19 +40,78 @@ pkg_setup() {
...
 	# Make main EFI
-	all_target=gnuefi
-	emake ARCH=${BUILDARCH} ${all_target}
+	use gnuefi && export all_target=gnuefi || export all_target=tiano
+	emake "${make_flags[@]}" ${all_target}
 
 	# Make filesystem drivers
-	export gnuefi_target="_gnuefi"
+	use gnuefi && export gnuefi_target="_gnuefi"
 	for fs in ${FS_USE}; do
```
Comment (SoapGentoo) [inline sys-boot/refind/refind-0.10.2.ebuild]: again, declare `local` before

File: sys-boot/udk/udk-2015.ebuild [hunk 4]
```diff
@@ -0,0 +1,241 @@
...
+	unpack "${WORKDIR}/${MY_V}.MyWorkSpace.zip"
+
+	pushd "${S}" || die
+	unpack "${WORKDIR}/BaseTools(Unix).tar"
+
+	local doc_name
+	if use doc; then
+		mkdir -p "${S}/doc" || die
+		pushd "${S}/doc" >/dev/null || die
+		for f in "${WORKDIR}/Documents/"*" Document.zip"; do
```
Comment (SoapGentoo) [inline sys-boot/udk/udk-2015.ebuild]: make `local`

File: sys-boot/refind/refind-0.10.2.ebuild [hunk 5]
```diff
@@ -39,19 +40,78 @@ pkg_setup() {
...
+			$(basename $(dirname ${f}))
+	done
+	for f in "${S}"/*/Make.tiano; do
+		sed -i -e 's@^\(EFILIB\s*=\s*\).*$@\1/usr/lib@' \
+			-e 's@\$(EFILIB).*/\([^/]*\).lib@-l\1@' \
+			-e 's/\(--start-group\s*\$(ALL_EFILIBS)\)/-L \$(EFILIB) \1/' \
+			"${f}" || die "Failed to patch Tianocore make file in" \
+			$(basename $(dirname ${f}))
+	done
+	sed -i -e '/Guids/i#include "AutoGen.h"\n' "${S}/filesystems/AutoGen.c"
```
Comment (gktrk) [inline sys-boot/refind/refind-0.10.2.ebuild]: missing ||die here

File: sys-boot/refind/refind-0.10.2.ebuild [hunk 6]
```diff
@@ -39,19 +40,78 @@ pkg_setup() {
...
+	for f in "${S}"/*/AutoGen.c; do
+		cat >>"${f}" <<EOF
```
Comment (gktrk) [inline sys-boot/refind/refind-0.10.2.ebuild]: missing ||die here

**Comment by sveyret** [comment]
Thank you all for your review. Just a short comment to warn you that I have an Internet breakdown for 2 weeks now and don't know when I will be able to work on it again.

**Comment by sveyret** [comment]
Hi,
Your suggestions are now included in the pull request.
Thank you!

File: sys-boot/refind/refind-0.10.2.ebuild [hunk 7]
```diff
@@ -39,19 +40,84 @@ pkg_setup() {
...
+		sed -i -e 's@^\(EFILIB\s*=\s*\).*$@\1/usr/lib@' \
+			-e 's@\$(EFILIB).*/\([^/]*\).lib@-l\1@' \
+			-e 's/\(--start-group\s*\$(ALL_EFILIBS)\)/-L \$(EFILIB) \1/' \
+			"${f}" || die "Failed to patch Tianocore make file in" \
+			$(basename $(dirname ${f}))
+	done
+	sed -i -e '/Guids/i#include "AutoGen.h"\n' "${S}/filesystems/AutoGen.c" \
+		|| die "Failed to patch AutoGen.c"
+	for f in "${S}"/*/AutoGen.c; do
+		(cat >>"${f}" <<EOF
```
Comment (SoapGentoo) [inline sys-boot/refind/refind-0.10.2.ebuild]: please just add the `|| die` after the EOF instead.

File: sys-boot/udk/udk-2015.ebuild [hunk 8]
```diff
@@ -0,0 +1,242 @@
...
+			fi
+		done
+		popd >/dev/null || die
+	fi
+
+	popd >/dev/null || die
+}
+
+src_configure() {
+	python_setup 'python2.7'
```
Comment (SoapGentoo) [inline sys-boot/udk/udk-2015.ebuild]: shouldn't this happen in `pkg_setup()` ?

File: sys-boot/udk/udk-2015.ebuild [hunk 9]
```diff
@@ -0,0 +1,242 @@
...
+		build_target=libraries
+	fi
+
+	build ${build_target} || die "Failed to compile environment"
+}
+
+src_install() {
+	local build_dir="${S}/Build/MdeModule/RELEASE_${TOOLCHAIN_TAG}/${ARCH}"
+
+	for f in "${build_dir}"/*/Library/*/*/OUTPUT/*.lib; do
```
Comment (SoapGentoo) [inline sys-boot/udk/udk-2015.ebuild]: make f `local`

**Comment by sveyret** [comment]
@SoapGentoo Thank you, all done…

**Comment by gktrk** [comment]
The build is failing for me:

```
x86_64-pc-linux-gnu-ld -o refind_x64.dll -n -q --gc-sections -nostdlib 			--script=/usr/lib/GccBase.lds 			--defsym=PECOFF_HEADER_SIZE=0x228 			--entry efi_main -u efi_main -m elf_x86_64 \
	  -L /usr/lib --start-group -lBaseDebugPrintErrorLevelLib -lBasePrintLib -lBasePcdLibNull -lUefiDebugLibStdErr -lBaseLib -lBaseMemoryLib -lUefiBootServicesTableLib -lUefiMemoryAllocationLib -lUefiRuntimeServicesTableLib -lUefiDevicePathLib -lUefiLib -lPeCoffExtraActionLibNull -lUefiApplicationEntryPoint -lDxeServicesLib -lDxeServicesTableLib -lDxeHobLib -lBasePeCoffLib apple.obj config.obj mystrings.obj line_edit.obj driver_support.obj icns.obj lib.obj main.obj menu.obj screen.obj gpt.obj crc32.obj legacy.obj AutoGen.obj ../libeg/libeg.lib \
	  ../EfiLib/EfiLib.lib ../mok/mok.lib --end-group
../libeg/libeg.lib(lodepng.obj): In function `lodepng_state_copy':
lodepng.c:(.text+0x4f65): undefined reference to `memcpy'
Make.tiano:48: recipe for target 'refind_x64.dll' failed
make[1]: *** [refind_x64.dll] Error 1
make[1]: Leaving directory '/var/tmp/portage/sys-boot/refind-0.10.3/work/refind-0.10.3/refind'
Makefile:54: recipe for target 'tiano' failed
make: *** [tiano] Error 2
```

First I thought removing `-nostdlib` may help, but it didn't. Am I missing something?

**Comment by sveyret** [comment]
@gktrk I will investigate, but I don't have this error, although I've got the exact same command executed. Which USE did you set ? Default ones ?

**Comment by sveyret** [comment]
@gktrk So, there is indeed a call to memcpy in lodepng.c, but it should not stay after compilation as memcpy is a #define in lodepng.h
Do you have a compilation option which would prevent from taking the good header file, or which would ignore the #define?

**Comment by sveyret** [comment]
So, after discussions in gentoo-proxy-maint channel, we have to try to replace #include string.h with stddef.h.

**Comment by gktrk** [comment]
shall we sed the sources on our end and file a bug upstream?

**Comment by gktrk** [comment]
let me know if you need my build logs

**Comment by sveyret** [comment]
@gktrk That's what I'll try. But as I don't have the problem in my machin, that would be good if you could do a test by your side so I'd be sure it works like that…

**Comment by gktrk** [comment]
sure, I'll get the logs, and also patch it and runtest tonight

**Comment by gktrk** [comment]
Interestingly, it did not fix the issue. I appended the following to src_prepare():
```
sed -i -e 's|<string.h>|<stddef.h>|' libeg/lodepng.h || die
```

but the build still fails. If I cd into ${WORKDIR}, do make clean && make it compiles file. Here's how we compile lodepng.o:

```
x86_64-pc-linux-gnu-gcc -O2 -pipe -march=native -fno-strict-aliasing -fno-stack-protector -fshort-wchar -Wall -DEFIX64 -DEFI_FUNCTION_WRAPPER -m64 -mno-red-zone  -fpic -I/usr/include/efi -I/usr/include/efi/x86_64 -I/usr/include/efi/protocol -I../include -I../refind -I../libeg -I../mok -I. -I./../include \
      -D__MAKEWITH_GNUEFI -DREFIND_VERSION='L"0.10.3"' -c lodepng.c -o lodepng.o
```

Here's the line after make clean && make:

```
/usr/bin/gcc -Os -fno-strict-aliasing -fno-stack-protector -fshort-wchar -Wall -DEFIX64 -DEFI_FUNCTION_WRAPPER -m64 -mno-red-zone  -fpic -I/usr/include/efi -I/usr/include/efi/x86_64 -I/usr/include/efi/protocol -I../include -I../refind -I../libeg -I../mok -I. -I./../include \
      -D__MAKEWITH_GNUEFI -DREFIND_VERSION='L"0.10.3"' -c lodepng.c -o lodepng.o
```

Here's our linker line:

```
x86_64-pc-linux-gnu-ld -L./../libeg/ -L./../mok/ -L./../EfiLib/ -T /usr/lib/elf_x86_64_efi.lds -shared -nostdlib -Bsymbolic 		-L/usr/lib -L/usr/lib /usr/lib/crt0-efi-x86_64.o -znocombreloc -zdefs  main.o mystrings.o apple.o line_edit.o config.o menu.o screen.o icns.o gpt.o crc32.o lib.o driver_support.o legacy.o \
      -o refind_x64.so -leg -lmok -lEfiLib -lefi -lgnuefi /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libgcc.a
```

Here's the linker line with make clean && make:

```
/usr/bin/ld -L./../libeg/ -L./../mok/ -L./../EfiLib/ -T /usr/lib/elf_x86_64_efi.lds -shared -Bsymbolic -nostdlib -L/usr/lib -L/usr/lib /usr/lib/crt0-efi-x86_64.o -znocombreloc -zdefs  main.o mystrings.o apple.o line_edit.o config.o menu.o screen.o icns.o gpt.o crc32.o lib.o driver_support.o legacy.o \
      -o refind_x64.so -leg -lmok -lEfiLib -lefi -lgnuefi /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libgcc.a
```

I have the following in `make.conf`:

```
CFLAGS="-O2 -pipe -march=native"
```

If I replace it with:

```
CFLAGS="-Os -pipe -march=native"
```

the compilation succeeds. Perhaps `-Os` is explicitly required?

**Comment by sveyret** [comment]
If I am not mistaking, my compilation line is exactly same as yours:
`x86_64-pc-linux-gnu-gcc -O2 -pipe -march=native -fno-strict-aliasing -fno-stack-protector -fshort-wchar -Wall -DEFIX64 -DEFI_FUNCTION_WRAPPER -m64 -mno-red-zone  -mcmodel=large "-DEFIAPI=__attribute__((ms_abi))"  -I /usr/include/udk -I .. -I ../refind -I ../libeg -I ../include -I ../mok -DNO_BUILTIN_VA_FUNCS \
      -D__MAKEWITH_TIANO -DREFIND_VERSION='L"0.10.3"' -c lodepng_xtra.c -o lodepng_xtra.obj
`
…and it's working! I can change the ebuild to force size optimization, if it really is an issue. Do you think I shall try that?

**Comment by gktrk** [comment]
We shouldn't needlessly force flags. I'll debug it some more tonight and test it on a different machine. Perhaps the problem is isolated to my setup.

**Comment by gktrk** [comment]
I can reproduce the error on a different machine which has `gcc version 4.9.3 (Gentoo 4.9.3 p1.4, pie-0.6.4)`. If I switch to `gcc version 4.8.5 (Gentoo 4.8.5 p1.3, pie-0.6.2)` on the same machine, it compiles fine.

**Comment by gktrk** [comment]
Issue persists with `gcc version 4.9.4 (Gentoo 4.9.4 p1.0, pie-0.6.4)`

**Comment by doughdemon** [comment]
The upstream commit https://sourceforge.net/p/refind/code/ci/430a0cb5b65d028351f2aa71f3bf3d225803d1fb/ looks relevant.

**Comment by sveyret** [comment]
For information, my version of gcc is `gcc (Gentoo 4.9.3 p1.5, pie-0.6.4) 4.9.3`. I'm not sure I'll have time to investigate the coming days, but I'd like to understand what the problem is… :-/

**Comment by sveyret** [comment]
After researching information on the web, the only thing I can think of is a problem of optimisation done by gcc, which seems to be confirmed by the options you tried to make it work. If I have time this week-end, I will try to disactivate optimisation for this file compilation.

**Comment by gktrk** [comment]
Compiles fine with `-O2` using `gcc version 4.10.0-pre9999 20160920 (experimental) commit ae96b054541acc606d6a9401aa4551f5ef53a21d (Gentoo 4.10.0_pre9999)`. Maybe we hit a regression?

**Comment by gktrk** [comment]
Somehow -O2 inserts a memcpy there during object creation:

```
        movq    %rbp, %rsi
-       rep movsl
-       leaq    80(%rbx), %r12
-       movq    %r13, %rdi
-       movabsq $lodepng_color_mode_init, %rax
-       call    *%rax
-       movq    %r12, %rdi
-       movabsq $lodepng_info_init, %rax
+       movq    %rbx, %rdi
+       movabsq $memcpy, %rax
        call    *%rax
```

Looks like a known gcc issue: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56888

**Comment by gktrk** [comment]
Reverting the commit in https://sourceforge.net/p/refind/code/ci/430a0cb5b65d028351f2aa71f3bf3d225803d1fb/ fixes it for me

**Comment by sveyret** [comment]
The commit was done for a compilation problem in ARM, so I think it is not a problem to revert for amd64/x86.
Solution 1: sed to simulate code revert if amd64 or x86.
Solution 2: sed to add a #if which ignore the #define if processor is amd64 or x86.
Solution 3: force -Os if gcc version is 4.9.x.
What do you think is best?

**Comment by gktrk** [comment]
Wish we know what the exact problem with arm was. I checked the preprocessor output of the file. Each reference to `memcpy` is successfully replaced with `MyMemCpy`. If I understand correctly, gcc emits extra `memcpy` during the optimization stage if it deems helpful. These are inserted past the preprocessing, so they are not converted properly with the `#define`. Once it hits the linking stage, because of `-nostdlib`, it fails. This wasn't a problem before because refind redefined `memcpy` instead of the redirection to `MyMemCpy` and the `memcpy` inserted by gcc are resolved correctly.

Refind isn't keyworded for `arm` at the moment, so we can just revert the code unconditionally. I should probably file an upstream bug about the issue.

**Comment by gktrk** [comment]
And we should revert with a patch instead of using sed to keep it more coherent. Bunch of sed statements will make little sense in the ebuild.

**Comment by sveyret** [comment]
@gktrk I made the patch, if you want to process a patch. I will also file a bug upstream.

**Comment by gktrk** [comment]
Sorry I am on vacation but I will test this in a day or two.

**Comment by gktrk** [comment]
Compiles fine with the our last patch

**Comment by gktrk** [comment]
So, I'm testing this on a hardened profile and udk fails for me with the following:

```
x86_64-pc-linux-gnu-gcc -o ../bin/GnuGenBootSector  GnuGenBootSector.o -L../libs -lCommon
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: GnuGenBootSector.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
GnuGenBootSector.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
../Makefiles/app.makefile:24: recipe for target '../bin/GnuGenBootSector' failed
make[2]: *** [../bin/GnuGenBootSector] Error 1
```

If I patch like the following, it compiles fine. Didn't get a chance to take a deeper look yet.

```
diff --git a/sys-boot/udk/udk-2015.ebuild b/sys-boot/udk/udk-2015.ebuild
index 5452d5f..cdbb6ad 100644
--- a/sys-boot/udk/udk-2015.ebuild
+++ b/sys-boot/udk/udk-2015.ebuild
@@ -72,6 +72,7 @@ src_configure() {
        append-cflags $(test-flags-CC -MD) $(test-flags-CC -fshort-wchar)
        append-cflags $(test-flags-CC -fno-strict-aliasing)
        append-cflags $(test-flags-CC -nostdlib) $(test-flags-CC -c)
+       append-cflags -fPIC
        sed -e "s:^\(CFLAGS\s*=\).*$:\1 ${CFLAGS}:" \
                -i "${S}/BaseTools/Source/C/Makefiles/header.makefile" \
                || die "Failed to update makefile header"
```

And refind fails with the following:

```
x86_64-pc-linux-gnu-ld -o refind_x64.dll -n -q --gc-sections -nostdlib 			--script=/usr/lib/GccBase.lds 			--defsym=PECOFF_HEADER_SIZE=0x228 			--entry efi_main -u efi_main -m elf_x86_64 \
	  -L /usr/lib --start-group -lBaseDebugPrintErrorLevelLib -lBasePrintLib -lBasePcdLibNull -lUefiDebugLibStdErr -lBaseLib -lBaseMemoryLib -lUefiBootServicesTableLib -lUefiMemoryAllocationLib -lUefiRuntimeServicesTableLib -lUefiDevicePathLib -lUefiLib -lPeCoffExtraActionLibNull -lUefiApplicationEntryPoint -lDxeServicesLib -lDxeServicesTableLib -lDxeHobLib -lBasePeCoffLib apple.obj config.obj mystrings.obj line_edit.obj driver_support.obj icns.obj lib.obj main.obj menu.obj screen.obj gpt.obj crc32.obj legacy.obj AutoGen.obj ../libeg/libeg.lib \
	  ../EfiLib/EfiLib.lib ../mok/mok.lib --end-group
line_edit.obj: In function `line_edit':
line_edit.c:(.text+0x475): undefined reference to `memmove'
line_edit.c:(.text+0x530): undefined reference to `memmove'
line_edit.c:(.text+0x6e6): undefined reference to `memmove'
Make.tiano:48: recipe for target 'refind_x64.dll' failed
make[1]: *** [refind_x64.dll] Error 1
make[1]: Leaving directory '/var/tmp/portage/sys-boot/refind-0.10.3/work/refind-0.10.3/refind'
Makefile:54: recipe for target 'tiano' failed
make: *** [tiano] Error 2
```

Working on that now.

**Comment by sveyret** [comment]
After reading some docs on gcc optimization, I added the -fno-tree-loop-distribute-patterns flag to gcc which prevents gcc from replacing some loops with standard memcpy, memmove, memset functions.
I think I managed to reproduice the problem and this flag corrects it. I modified my commits in order to use this new method. Please tell me if everything is working now.
P.S. Will work on 0.10.4 after that.

**Comment by mgorny** [comment]
@sveyret, the gcc bug report actually talks of `-ffreestanding` flag. AFAIU it prevents the compiler from generating any builtin function calls. Isn't that what you want here?

**Comment by sveyret** [comment]
@mgorny If I understood well, even a freestanding system must have a memcpy, memmove, etc. functions, and so gcc is replacing code by calls to these functions during its optimization process. In the issue given by @gktrk , the reporter says he *is* using -ffreestanding and has the problem anyway.

**Comment by gktrk** [comment]
The sed in src_unpack of udk fails with:

```
Appending /home/gokturk/stuff/gentoo to PORTDIR_OVERLAY...
 * UDK2015.Complete.MyWorkSpace.zip SHA256 SHA512 WHIRLPOOL size ;-) ... [ ok ]
>>> Unpacking source...
>>> Unpacking UDK2015.Complete.MyWorkSpace.zip to /var/tmp/portage/sys-boot/udk-2015/work
>>> Unpacking /var/tmp/portage/sys-boot/udk-2015/work/UDK2015.MyWorkSpace.zip to /var/tmp/portage/sys-boot/udk-2015/work
/var/tmp/portage/sys-boot/udk-2015/work/MyWorkSpace /var/tmp/portage/sys-boot/udk-2015/work
>>> Unpacking /var/tmp/portage/sys-boot/udk-2015/work/BaseTools(Unix).tar to /var/tmp/portage/sys-boot/udk-2015/work/MyWorkSpace
sed: -e expression #1, char 31: invalid reference \1 on `s' command's RHS
sed: -e expression #1, char 31: invalid reference \1 on `s' command's RHS
sed: -e expression #1, char 31: invalid reference \1 on `s' command's RHS
sed: -e expression #1, char 31: invalid reference \1 on `s' command's RHS
sed: -e expression #1, char 31: invalid reference \1 on `s' command's RHS
>>> Source unpacked in /var/tmp/portage/sys-boot/udk-2015/work
```

It's missing the escapes on `( )` for the submatch:

```
 sys-boot/udk/udk-2015.ebuild | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/sys-boot/udk/udk-2015.ebuild b/sys-boot/udk/udk-2015.ebuild
index b758cf7..b3023dd 100644
--- a/sys-boot/udk/udk-2015.ebuild
+++ b/sys-boot/udk/udk-2015.ebuild
@@ -53,7 +53,7 @@ src_unpack() {
 		mkdir -p "${S}/doc" || die
 		pushd "${S}/doc" >/dev/null || die
 		for f in "${WORKDIR}/Documents/"*" Document.zip"; do
-			doc_name=$(echo ${f} | sed -e 's:^.*/([^/]*) Document.zip$:\1:')
+			doc_name=$(echo ${f} | sed -e 's:^.*/\([^/]*\) Document.zip$:\1:')
 			if [[ -f "${WORKDIR}/Documents/${doc_name} Document.zip" ]]; then
 				unpack "${WORKDIR}/Documents/${doc_name} Document.zip"
 				mv "${S}/doc/html" "${S}/doc/${doc_name}" || die
```

will fix it here before commit

**Comment by gktrk** [comment]
should also put that `.` before `zip` in `[ ]` for an exact match on `.`

**Comment by gktrk** [comment]
(drum rolls ...)

Merged in https://github.com/gentoo/gentoo/compare/ffcd38e...431a8c3! Thanks for being patient with us and apologies for the crazy delay.
