### PR TITLE
sci-libs/dlib: add 19.24.8

### PR DESCRIPTION
**Pull request by kcning**
This PR addresses the following issues:
1. enable Python 3.13
2. fix compability issue with numpy 2
3. upgrade to the latest release

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by Nowa-Ammerlaan** [comment]
I'm getting a build failure that seems to be related to `ffmpeg-7`:
```
/tmp/portage/sci-libs/dlib-19.24.8/work/dlib-19.24.8/dlib/../dlib/media/ffmpeg_muxer.h:814:80: error: ‘AVCodec::ch_layouts’ is deprecated [-Werror=deprecated-declarations]
814 |                         av_channel_layout_copy(&pCodecCtx->ch_layout, &pCodec->ch_layouts[0]);
|                                                                                ^~~~~~~~~~
/usr/include/libavcodec/codec.h:241:28: note: declared here
241 |     const AVChannelLayout *ch_layouts;
|                            ^~~~~~~~~~
/tmp/portage/sci-libs/dlib-19.24.8/work/dlib-19.24.8/dlib/../dlib/media/ffmpeg_muxer.h:814:80: error: ‘AVCodec::ch_layouts’ is deprecated [-Werror=deprecated-declarations]
814 |                         av_channel_layout_copy(&pCodecCtx->ch_layout, &pCodec->ch_layouts[0]);
|                                                                                ^~~~~~~~~~
/usr/include/libavcodec/codec.h:241:28: note: declared here
241 |     const AVChannelLayout *ch_layouts;
|                            ^~~~~~~~~~
/tmp/portage/sci-libs/dlib-19.24.8/work/dlib-19.24.8/dlib/../dlib/media/ffmpeg_muxer.h:814:80: error: ‘AVCodec::ch_layouts’ is deprecated [-Werror=deprecated-declarations]
814 |                         av_channel_layout_copy(&pCodecCtx->ch_layout, &pCodec->ch_layouts[0]);
|                                                                                ^~~~~~~~~~
/usr/include/libavcodec/codec.h:241:28: note: declared here
241 |     const AVChannelLayout *ch_layouts;
|                            ^~~~~~~~~~
cc1plus: all warnings being treated as errors
[342/472] /usr/bin/x86_64-pc-linux-gnu-g++  -I/us
```
Possibly there is also a missing dependency on ffmpeg. It's also adding `-Werror` by itself, which it should not do.

**Comment by kcning** [comment]
The PR builds with ```media-video/ffmpeg-7.1.1``` as it is.

Adding ```-Werror``` is its own behavior, I think it's not in the scope of this PR, and would be better to be addressed in another PR.

I can add ffmpeg as a dependency, thank you for pointing it out. I thought that I didn't have to check every details in the old ebuild because it is maintained by Gentoo Science Project.

**Comment by Nowa-Ammerlaan** [comment]
> The PR builds with `media-video/ffmpeg-7.1.1` as it is.

But if it uses ffmpeg stuff during the build, then at some point it must depend on ffmpeg. Or am I missing something here?

> Adding `-Werror` is its own behavior, I think it's not in the scope of this PR, and would be better to be addressed in another PR.

Normally I'd agree with this, but as it is, this build failure I am encountering is preventing me from actually testing this PR, and therefore I cannot merge it.

**Comment by kcning** [comment]
Please provide the following info
1. ```emerge --info ffmpeg```
2. build.log

**Comment by Nowa-Ammerlaan** [comment]
[build.txt](https://github.com/user-attachments/files/19618152/build.txt)
[emerge-info.txt](https://github.com/user-attachments/files/19618153/emerge-info.txt)

**Comment by kcning** [comment]
Thank you. The ```-Werror``` option is added by the upsteam source:```dlib/test/CMakelists.txt:173```. I cannot see your ffmpeg version but from what you wrote I assume it's 7.1.1 too. One difference between our machines is that you're on gcc 13 and I'm on 14, but I'm not sure exactly why CMake add the option for you but not for me.

**Comment by Nowa-Ammerlaan** [comment]
> One difference between our machines is that you're on gcc 13 and I'm on 14, but I'm not sure exactly why CMake adds the option for you but not for me.

It could be the `test` USE flag.

File: sci-libs/dlib/files/dlib-19.24.8-disable-upstream-flags.patch [hunk 1]
```diff
@@ -0,0 +1,111 @@
+diff --git a/dlib/test/CMakeLists.txt b/dlib/test/CMakeLists.txt
+index 330ac241..6a3ad681 100644
+--- a/dlib/test/CMakeLists.txt
++++ b/dlib/test/CMakeLists.txt
+@@ -168,56 +168,56 @@ add_executable(${target_name} main.cpp tester.cpp
+ get_filename_component(DLIB_FFMPEG_DATA ${CMAKE_SOURCE_DIR}/ffmpeg_data/details.cfg REALPATH)
+ target_compile_definitions(${target_name} PRIVATE DLIB_FFMPEG_DATA="${DLIB_FFMPEG_DATA}")
+ 
+-if (CMAKE_COMPILER_IS_GNUCXX)
```
Comment (Nowa-Ammerlaan) [inline sci-libs/dlib/files/dlib-19.24.8-disable-upstream-flags.patch:9]: We technically only need to patch this line and make the if statement fail unconditionally. This would make the patch a lot shorter.

File: sci-libs/dlib/files/dlib-19.24.8-disable-upstream-flags.patch [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+-
+-   if(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.13.0") 
+-      # strip debug symbols to make the binary smaller
+-      target_link_options(${target_name} PRIVATE $<$<CONFIG:RELEASE>:-s>)
+-   endif()
+-
+-elseif (MSVC)
+-   # Treat warnings as errors.
+-   add_compile_options(/WX)
+-else() # basically Clang
```
Comment (kcning) [inline sci-libs/dlib/files/dlib-19.24.8-disable-upstream-flags.patch:48]: the 'else' clause

Comment (Nowa-Ammerlaan) [reply sci-libs/dlib/files/dlib-19.24.8-disable-upstream-flags.patch:48]: Well then we can make this an elif that also fails always.

The point is this patch is unnecessarily huge because it is commenting a large block of code, it could already be shorter by removing this block of code instead of commenting it. Or it could be even shorter by simply rendering it ineffective with some if.

**Comment by Nowa-Ammerlaan** [comment]
Thanks :+1: 

I added an `ffmpeg` flag to toggle the ffmpeg requirement since it has a significant effect on the built time. I also found that `webp` was another automagic dependency.

**Comment by kcning** [comment]
Yes, you're right. And thank you too!
