### PR TITLE
dev-db/redis: build fix for luajit-2.1

### PR DESCRIPTION
**Pull request by arkamar**
Versions with unbundled lua fail to build with `dev-lang/luajit-2.1` with an error message:
```
lua_cjson.c:1300:13: error: static declaration of 'luaL_setfuncs' follows non-static declaration
 1300 | static void luaL_setfuncs (lua_State *l, const luaL_Reg *reg, int nup)
      |             ^~~~~~~~~~~~~
```
This PR fixes this by backporting patch from `lua-cjson` upstream to bundled one (Yes, it sounds weird but we have unbundled lua, but few extensions like `lua-cjson` are still bundled). See commit message for slightly more info.

Additionally, I am joining you as a proxy co-maintainer ;)

### CODE REVIEW

File: dev-db/redis/metadata.xml [hunk 1]
```diff
@@ -1,10 +1,14 @@
 <?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
 <pkgmetadata>
-	<maintainer type="person">
+	<maintainer type="person" proxied="proxy">
```
Comment (thesamesam) [inline dev-db/redis/metadata.xml:4]: FWIW, and this is confusing, this actually means I don't maintain it in my own right IIRC: https://gitweb.gentoo.org/data/glep.git/commit/?id=824f0fcd9a466ca69e9705bd2f380ccac768151a

So, I'll drop that part, and also put you first, just because I've been feeling guilty about the attention (or lack of) I've been giving to Redis, and you've been doing a good job. Happy to change it though.
