### PR TITLE
Fixup gns3 and deps

### PR DESCRIPTION
**Pull request by oniGino**
An effort to keep gns3-server and gns3-gui in portage tree

required me to bump versions on several packages that I am not the maintainer of.
and for one package add an older version that was not currently in tree

Closes: https://bugs.gentoo.org/688016

### CODE REVIEW

File: dev-python/aiohttp/aiohttp-3.6.2.ebuild [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+
+CDEPEND="
+	>=dev-python/async_timeout-3.0.0[${PYTHON_USEDEP}]
+	>=dev-python/attrs-17.3.0[${PYTHON_USEDEP}]
+	dev-python/chardet[${PYTHON_USEDEP}]
+	>=dev-python/multidict-4.5.0[${PYTHON_USEDEP}]
+	>=dev-python/yarl-1.0[${PYTHON_USEDEP}]
+	dev-python/idna-ssl[${PYTHON_USEDEP}]
+	$(python_gen_cond_dep 'dev-python/typing-extensions[${PYTHON_USEDEP}]' \
+		python3_{5,6})
```
Comment (juippis) [inline dev-python/aiohttp/aiohttp-3.6.2.ebuild:28]: I believe this is not needed here.

File: dev-python/aiohttp/aiohttp-3.6.2.ebuild [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+"
+DEPEND="
+	dev-python/setuptools[${PYTHON_USEDEP}]
```
Comment (juippis) [inline dev-python/aiohttp/aiohttp-3.6.2.ebuild:31]: Handled via *distutils-r1.eclass* and can be removed.

File: dev-python/aiohttp/aiohttp-3.6.2.ebuild [hunk 3]
```diff
@@ -0,0 +1,77 @@
...
+	dev-python/cython[${PYTHON_USEDEP}]
+	doc? (
+		>=dev-python/alabaster-0.6.2[${PYTHON_USEDEP}]
+		dev-python/sphinxcontrib-asyncio[${PYTHON_USEDEP}]
+		dev-python/sphinxcontrib-blockdiag[${PYTHON_USEDEP}]
+		dev-python/sphinxcontrib-newsfeed[${PYTHON_USEDEP}]
+		dev-python/sphinxcontrib-spelling[${PYTHON_USEDEP}]
+		dev-python/sphinx[${PYTHON_USEDEP}]
+		dev-python/sphinx-aiohttp-theme[${PYTHON_USEDEP}]
```
Comment (juippis) [inline dev-python/aiohttp/aiohttp-3.6.2.ebuild:40]: You could try to use *distutils-r1.eclass* for doc creating.

File: dev-python/aiohttp/aiohttp-3.6.2.ebuild [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+HOMEPAGE="https://pypi.org/project/aiohttp/"
+SRC_URI="mirror://pypi/${P:0:1}/${PN}/${P}.tar.gz"
+
+LICENSE="Apache-2.0"
+SLOT="0"
+KEYWORDS="~amd64 ~arm ~arm64 x86"
+IUSE="doc test"
+RESTRICT="!test? ( test )"
+
+CDEPEND="
```
Comment (juippis) [inline dev-python/aiohttp/aiohttp-3.6.2.ebuild:20]: Also please don't use `CDEPEND` but `COMMON_DEPEND` instead.

File: dev-python/aiohttp/aiohttp-3.6.2.ebuild [hunk 5]
```diff
@@ -0,0 +1,77 @@
...
+	distutils-r1_python_prepare_all
+}
+
+python_compile_all() {
+	use doc && emake -C docs html
+}
+
+python_test() {
+	pytest -vv || die "Tests fail with ${EPYTHON}"
+}
```
Comment (juippis) [inline dev-python/aiohttp/aiohttp-3.6.2.ebuild:71]: You can try to use the *distutils-r1.eclass* test function. This looks so simple it should work.

File: dev-python/raven/raven-6.10.0.ebuild [hunk 6]
```diff
@@ -0,0 +1,23 @@
+# Copyright 1999-2020 Gentoo Authors
+# Distributed under the terms of the GNU General Public License v2
+
+EAPI=7
+
+PYTHON_COMPAT=( python3_7 python3_8 )
```
Comment (juippis) [inline dev-python/raven/raven-6.10.0.ebuild:6]: Hmm, I wonder if dropping python3.6 will make it harder to update revdeps etc. Just include it here until it's dropped tree-wide.

**Comment by oniGino** [comment]
@juippis ok this should be good, aiohttp seems to build without issue

File: dev-python/aiohttp/aiohttp-3.6.2.ebuild [hunk 7]
```diff
@@ -0,0 +1,68 @@
...
+		dev-python/async_generator[${PYTHON_USEDEP}]
+		dev-python/brotlipy[${PYTHON_USEDEP}]
+		>=dev-python/pytest-3.4.0[${PYTHON_USEDEP}]
+		dev-python/pytest-mock[${PYTHON_USEDEP}]
+		dev-python/pytest-timeout[${PYTHON_USEDEP}]
+		dev-python/trustme[${PYTHON_USEDEP}]
+		www-servers/gunicorn[${PYTHON_USEDEP}]
+	)
+"
+RDEPEND="${CDEPEND}"
```
Comment (juippis) [inline dev-python/aiohttp/aiohttp-3.6.2.ebuild:41]: `COMMON_DEPEND`

File: dev-python/aiohttp/aiohttp-3.6.2.ebuild [hunk 8]
```diff
@@ -0,0 +1,68 @@
...
+
+DOCS=( CHANGES.rst CONTRIBUTORS.txt README.rst )
+
+python_prepare_all() {
+	# FIXME
```
Comment (juippis) [inline dev-python/aiohttp/aiohttp-3.6.2.ebuild:46]: You probably want to update this comment to tell what the sed below is doing.

File: dev-python/aiohttp/aiohttp-3.6.2.ebuild [hunk 9]
```diff
@@ -0,0 +1,68 @@
...
+distutils_enable_sphinx docs \
+	'>=dev-python/alabaster-0.6.2' \
+	'dev-python/sphinxcontrib-asyncio' \
+	'dev-python/sphinxcontrib-blockdiag' \
+	'dev-python/sphinxcontrib-newsfeed' \
+	'dev-python/sphinxcontrib-spelling' \
+	'dev-python/sphinx' \
+	'dev-python/sphinx-aiohttp-theme'
+
+distutils_enable_tests pytest || die "Tests fail with ${EPYTHON}"
```
Comment (juippis) [inline dev-python/aiohttp/aiohttp-3.6.2.ebuild:62]: These are usually defined before any `src*` or `pkg*` phase.

File: dev-python/aiohttp/aiohttp-3.6.2.ebuild [hunk 10]
```diff
@@ -0,0 +1,68 @@
...
+
+python_install_all() {
+	use doc && local HTML_DOCS=( docs/_build/html/. )
+
+	distutils-r1_python_install_all
```
Comment (juippis) [inline dev-python/aiohttp/aiohttp-3.6.2.ebuild:67]: The `distutils_enable_sphinx docs` should handle everything here all right, so you can remove the phase from this ebuild.

File: dev-python/aiohttp/aiohttp-3.6.2.ebuild (hunk 9 above)
Comment (juippis) [inline dev-python/aiohttp/aiohttp-3.6.2.ebuild:62]: `|| die` is not needed here.

I can't get the tests to run, 
```
>>> Test phase: dev-python/aiohttp-3.6.2
 * python3_6: running distutils-r1_run_phase python_test
================================== test session starts ==================================
platform linux -- Python 3.6.10, pytest-4.6.9, py-1.8.0, pluggy-0.13.1 -- /usr/bin/python3.6
cachedir: .pytest_cache
rootdir: /tmp/portage/dev-python/aiohttp-3.6.2/work/aiohttp-3.6.2
plugins: asyncio-0.11.0, timeout-1.3.4, mock-3.1.0
collecting ... collected 415 items / 46 errors / 369 selected

======================================== ERRORS =========================================
________________________ ERROR collecting aiohttp/test_utils.py _________________________
import file mismatch:
imported module 'aiohttp.test_utils' has this __file__ attribute:
  /tmp/portage/dev-python/aiohttp-3.6.2/work/aiohttp-3.6.2-python3_6/lib/aiohttp/test_utils.py
which is not the same as the test file we want to collect:
  /tmp/portage/dev-python/aiohttp-3.6.2/work/aiohttp-3.6.2/aiohttp/test_utils.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
_____________________ ERROR collecting tests/test_base_protocol.py ______________________
/usr/lib64/python3.6/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
/usr/lib64/python3.6/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib64/python3.6/site-packages/pluggy/manager.py:87: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
/usr/lib64/python3.6/site-packages/_pytest/python.py:204: in pytest_pycollect_makeitem
    res = outcome.get_result()
/usr/lib64/python3.6/site-packages/pytest_asyncio/plugin.py:39: in pytest_pycollect_makeitem
    item = pytest.Function.from_parent(collector, name=name)
E   AttributeError: type object 'Function' has no attribute 'from_parent'
```
and this error repeats like 46 times. Any ideas? It also complained something about the file you modify with `sed` in this ebuild. Could it be related?

Comment (zmedico) [reply dev-python/aiohttp/aiohttp-3.6.2.ebuild:55]: The `AttributeError: type object 'Function' has no attribute 'from_parent'` means that you need to upgrade to at least pytest-5.4. A dependency should be added to the pytest-asyncio ebuild.

Comment (zmedico) [reply dev-python/aiohttp/aiohttp-3.6.2.ebuild:55]: I've fixed the pytest-asyncio dep in 93b9fca29cccb66846a5b95edc96fd05171c777a.

I've merged the aiohttp version bump in eb5c65238c8c617f2a7c3b88ca2af7e16a88fde0, and the aiofile ebuild in 7c34cc5a6165b8182ddc1614b1148f8b7fdd3554.

**Comment by oniGino** [comment]
Several changes here
- 2.2.9999 for python 3.8 compat
- 2.2.8 is latest stable and builds on python3.7
- psutil 5.6.6 is required for gns3-server
- latest raven is a good idea for python 3.7+

File: net-misc/gns3-server/gns3-server-2.2.8.ebuild [hunk 11]
```diff
@@ -0,0 +1,63 @@
...
+	>=dev-python/jinja-2.7.3[${PYTHON_USEDEP}]
+	python_targets_python3_7? ( ~dev-python/jsonschema-2.6.0[${PYTHON_USEDEP}] )
+	python_targets_python3_8? ( ~dev-python/jsonschema-3.2.0[${PYTHON_USEDEP}] )
+	~dev-python/psutil-5.6.6[${PYTHON_USEDEP}]
+	~dev-python/py-cpuinfo-5.0.0[${PYTHON_USEDEP}]
+	>=dev-python/raven-5.23.0[${PYTHON_USEDEP}]
+	>=net-misc/ubridge-0.9.14
+	qemu? ( app-emulation/qemu )
+"
+DEPEND="dev-python/setuptools[${PYTHON_USEDEP}]"
```
Comment (juippis) [inline net-misc/gns3-server/gns3-server-2.2.8.ebuild:36]: Handled by *distutils-r1.eclass*.

File: net-misc/gns3-server/gns3-server-2.2.8.ebuild [hunk 12]
```diff
@@ -0,0 +1,63 @@
...
+	>=dev-python/distro-1.3.0[${PYTHON_USEDEP}]
+	>=app-emulation/dynamips-0.2.18
+	>=dev-python/jinja-2.7.3[${PYTHON_USEDEP}]
+	python_targets_python3_7? ( ~dev-python/jsonschema-2.6.0[${PYTHON_USEDEP}] )
+	python_targets_python3_8? ( ~dev-python/jsonschema-3.2.0[${PYTHON_USEDEP}] )
+	~dev-python/psutil-5.6.6[${PYTHON_USEDEP}]
+	~dev-python/py-cpuinfo-5.0.0[${PYTHON_USEDEP}]
+	>=dev-python/raven-5.23.0[${PYTHON_USEDEP}]
+	>=net-misc/ubridge-0.9.14
+	qemu? ( app-emulation/qemu )
```
Comment (juippis) [inline net-misc/gns3-server/gns3-server-2.2.8.ebuild:34]: This doesn't seem to have any function in this ebuild.
https://projects.gentoo.org/qa/policy-guide/dependencies.html#pg0001

File: net-misc/gns3-gui/gns3-gui-2.2.8.ebuild [hunk 13]
```diff
@@ -0,0 +1,48 @@
...
+inherit distutils-r1 desktop xdg-utils
+
+DESCRIPTION="Graphical Network Simulator"
+HOMEPAGE="http://www.gns3.net/"
+SRC_URI="https://github.com/GNS3/${PN}/archive/v${PV}.tar.gz -> ${P}.tar.gz"
+
+LICENSE="GPL-3+"
+SLOT="0"
+KEYWORDS="~amd64 ~x86"
+IUSE="server"
```
Comment (juippis) [inline net-misc/gns3-gui/gns3-gui-2.2.8.ebuild:17]: This doesn't do anything. 
https://projects.gentoo.org/qa/policy-guide/dependencies.html#pg0001

File: net-misc/gns3-gui/gns3-gui-2.2.8.ebuild [hunk 14]
```diff
@@ -0,0 +1,48 @@
...
+	python_targets_python3_6? ( ~dev-python/jsonschema-2.6.0[${PYTHON_USEDEP}] )
+	python_targets_python3_7? ( ~dev-python/jsonschema-2.6.0[${PYTHON_USEDEP}] )
+	python_targets_python3_8? ( ~dev-python/jsonschema-3.2.0[${PYTHON_USEDEP}] )
+	>=dev-python/raven-5.23.0[${PYTHON_USEDEP}]
+	~dev-python/psutil-5.6.6[${PYTHON_USEDEP}]
+	>=dev-python/distro-1.3.0[${PYTHON_USEDEP}]
+	server? ( ~net-misc/gns3-server-${PV}[${PYTHON_USEDEP}] )
+	dev-python/PyQt5[gui,network,svg,websockets,widgets,${PYTHON_USEDEP}]
+"
+DEPEND="dev-python/setuptools[${PYTHON_USEDEP}]"
```
Comment (juippis) [inline net-misc/gns3-gui/gns3-gui-2.2.8.ebuild:31]: Handled by *distutils-r1.eclass*.

File: dev-python/psutil/psutil-5.6.6.ebuild [hunk 15]
```diff
@@ -0,0 +1,49 @@
...
+
+inherit distutils-r1
+
+DESCRIPTION="Retrieve information on running processes and system utilization"
+HOMEPAGE="https://github.com/giampaolo/psutil https://pypi.org/project/psutil/"
+SRC_URI="mirror://pypi/${PN:0:1}/${PN}/${P}.tar.gz"
+
+LICENSE="BSD"
+SLOT="0"
+KEYWORDS="~alpha amd64 arm arm64 hppa ~ia64 ppc ppc64 s390 sparc x86 ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x86-macos ~sparc-solaris ~sparc64-solaris ~x64-solaris ~x86-solaris"
```
[the remark this answers is not in the document]
Comment (oniGino) [reply dev-python/psutil/psutil-5.6.6.ebuild:15]: sorry your frustrated, If your wondering why psutil-5.6.6 looks this way its because its an identical copy of psutil-5.7.0, WHICH I DID NOT WRITE! and has been in tree for some time now.

I am also not thrilled about having to fix a bunch of python deps that I don't actually care about. I'm taking ownership of to fix some other packages.

Lack of maintainer-ship is Gentoo is not an easy thing, so we are all trying to contribute where we can.

Thanks for being patient

File: dev-python/psutil/psutil-5.6.6.ebuild [hunk 16]
```diff
@@ -0,0 +1,49 @@
...
+	test? (
+		$(python_gen_cond_dep '
+			dev-python/mock[${PYTHON_USEDEP}]
+			dev-python/ipaddress[${PYTHON_USEDEP}]
+		' -2)
+	)
+"
+
+PATCHES=(
+	"${FILESDIR}/psutil-5.6.6-tests.patch"
```
[the remark this answers is not in the document]
Comment (oniGino) [reply dev-python/psutil/psutil-5.6.6.ebuild:30]: why would you want to keep "psutil-5.6.7-tests.patch" when no psutil-5.6.7 ebuild even exists?
seems it should have been removed from tree a while ago

File: net-misc/gns3-server/gns3-server-2.2.8.ebuild (hunk 12 above)
Comment (oniGino) [reply net-misc/gns3-server/gns3-server-2.2.8.ebuild:34]: a GNS3 user could easily argue that gns3-server is basically useless without some virtualization KVM, qemu being the most commonly used

Comment (oniGino) [reply net-misc/gns3-server/gns3-server-2.2.8.ebuild:34]: I'll drop the dep though for simplicitys sake

Comment (juippis) [reply net-misc/gns3-server/gns3-server-2.2.8.ebuild]: You should use `optfeature` for it, as stated in the link. This kind of usage is banned by QA.

File: dev-python/psutil/psutil-5.6.6.ebuild (hunk 16 above)
[the remark this answers is not in the document]
Comment (juippis) [reply dev-python/psutil/psutil-5.6.6.ebuild]: Could be Github... but it showed that you are renaming `psutil-5.6.7-tests.patch` to `psutil-5.6.6-tests.patch`. You don't have to rename it, you can just call `psutil-5.6.7-tests.patch` in here.

[the remark this answers is not in the document]
Comment (oniGino) [reply dev-python/psutil/psutil-5.6.6.ebuild]: ok i left the file name the same

File: net-misc/gns3-server/gns3-server-2.2.8.ebuild (hunk 12 above)
Comment (oniGino) [reply net-misc/gns3-server/gns3-server-2.2.8.ebuild]: thank you, I was unaware of this in eutils

**Comment by juippis** [comment]
Just a quick question: Does it really need psutil-5.6.6? Or is upstream just overly restrictive with deps? If you try to patch their requirement file to accept >=5.6.7, does the program work, or will it crash? 

Just asking because psutil is maintained by python, and they might think what's happening when suddenly older versions are brought back.

Also you don't have to become a maintainer for dependencies, but then you will miss bug reports, and if they aren't handled, those deps might be a suspect for removal.

**Comment by oniGino** [comment]
> Just a quick question: Does it really need psutil-5.6.6? Or is upstream just overly restrictive with deps? If you try to patch their requirement file to accept >=5.6.7, does the program work, or will it crash?
> 
> Just asking because psutil is maintained by python, and they might think what's happening when suddenly older versions are brought back.
> 
> Also you don't have to become a maintainer for dependencies, but then you will miss bug reports, and if they aren't handled, those deps might be a suspect for removal.

did some testing against 5.7.0 it seems to run fine, adding a sed line and pushing again

**Comment by oniGino** [comment]
@flappyports I guess this isn't needed, and I'm no longer maintainer? thanks for the heads up. 
If your wondering why gentoo has trouble keeping maintainers its stuff like this.

Hope I was of some help.

**Comment by juippis** [comment]
I'm sorry, this is 100 % on me. I haven't had time to do much Gentoo-related work lately. 

I see we need to handle workflow / communication between devs better in future. I should've taken the mask off when I saw there was a serious attempt to fix it (we have a history where we do this, then contributor vanishes and the package needs to be last-rited AGAIN).

If you still wish to maintain this, we can continue to work on this PR. I haven't had time to check your latest changes, and most likely won't have before tomorrow, but you were so close I believe we can re-introduce this to ::gentoo repo.

**Comment by flappyports** [comment]
@oniGino my apologies for not seeing this PR. I will happily give you maintainer-ship back. I simply needed to use the software and saw it was long out of date.
