### PR TITLE
www-servers/apache: Fix build with >=dev-libs/libxml2-2.12.0

### PR DESCRIPTION
**Pull request by inode64**
See the pull
https://github.com/apache/httpd/pull/393

### CODE REVIEW

**Comment by thesamesam** [comment]
The patch seems kind of weird but it got merged upstream and the discussion there makes sense at a glance.

**Comment by inode64** [comment]
This partch solve this error
<pre>
/usr/share/apr/build/libtool --silent --mode=link x86_64-pc-linux-gnu-gcc -I/usr/include/libxml2   -O3 -march=haswell -pipe -fgraphite-identity -floop-nest-optimize -fomit-frame-pointer     -Wl,-O1 -Wl,--as-needed -Wl,--no-as-needed    -o mod_buffer.la -rpath /usr/lib64/apache2/modules -module -avoid-version  mod_buffer.lo 
/usr/share/apr/build/libtool --silent --mode=link x86_64-pc-linux-gnu-gcc -I/usr/include/libxml2   -O3 -march=haswell -pipe -fgraphite-identity -floop-nest-optimize -fomit-frame-pointer     -Wl,-O1 -Wl,--as-needed -Wl,--no-as-needed    -o mod_ratelimit.la -rpath /usr/lib64/apache2/modules -module -avoid-version  mod_ratelimit.lo 
/usr/share/apr/build/libtool --silent --mode=link x86_64-pc-linux-gnu-gcc -I/usr/include/libxml2   -O3 -march=haswell -pipe -fgraphite-identity -floop-nest-optimize -fomit-frame-pointer     -Wl,-O1 -Wl,--as-needed -Wl,--no-as-needed    -o mod_reqtimeout.la -rpath /usr/lib64/apache2/modules -module -avoid-version  mod_reqtimeout.lo 
mod_xml2enc.c: In function 'sniff_encoding':
mod_xml2enc.c:212:53: error: unknown type name 'xmlChar'
  212 |         ctx->xml2enc = xmlDetectCharEncoding((const xmlChar*)ctx->buf,
      |                                                     ^~~~~~~
make[4]: *** [/var/tmp/portage/www-servers/apache-2.4.58/work/httpd-2.4.58/build/rules.mk:212: mod_xml2enc.slo] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/var/tmp/portage/www-servers/apache-2.4.58/work/httpd-2.4.58/modules/filters'
make[3]: *** [/var/tmp/portage/www-servers/apache-2.4.58/work/httpd-2.4.58/build/rules.mk:117: shared-build-recursive] Error 1
make[3]: Leaving directory '/var/tmp/portage/www-servers/apache-2.4.58/work/httpd-2.4.58/modules/filters'
make[2]: *** [/var/tmp/portage/www-servers/apache-2.4.58/work/httpd-2.4.58/build/rules.mk:117: shared-build-recursive] Error 1
make[2]: Leaving directory '/var/tmp/portage/www-servers/apache-2.4.58/work/httpd-2.4.58/modules'
make[1]: *** [/var/tmp/portage/www-servers/apache-2.4.58/work/httpd-2.4.58/build/rules.mk:117: shared-build-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/www-servers/apache-2.4.58/work/httpd-2.4.58'
make: *** [/var/tmp/portage/www-servers/apache-2.4.58/work/httpd-2.4.58/build/rules.mk:75: all-recursive] Error 1
 * ERROR: www-servers/apache-2.4.58::gentoo failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=www-servers/apache-2.4.58::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=www-servers/apache-2.4.58::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/www-servers/apache-2.4.58/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/www-servers/apache-2.4.58/temp/environment'.
 * Working directory: '/var/tmp/portage/www-servers/apache-2.4.58/work/httpd-2.4.58'
 * S: '/var/tmp/portage/www-servers/apache-2.4.58/work/httpd-2.4.58'

</pre>

It is the same problem that was solved in Postgres
https://bugs.gentoo.org/923633
