### PR TITLE
sci-libs/ginkgo: add hip useflag

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**
Closes: https://bugs.gentoo.org/814845
Signed-off-by: Alessandro Barbieri <lssndrbarbieri@gmail.com>

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
I'm getting the following configure error when I try to build with `USE="hip"`:
```
-- ROCclr at /usr/lib/cmake/rocclr
-- hip::amdhip64 is SHARED_LIBRARY
-- ROCclr at /usr/lib/cmake/rocclr
-- hip::amdhip64 is SHARED_LIBRARY
-- ROCclr at /usr/lib/cmake/rocclr
-- hip::amdhip64 is SHARED_LIBRARY
CMake Error at hip/CMakeLists.txt:246 (hip_add_library):
Unknown CMake command "hip_add_library".


-- Configuring incomplete, errors occurred!
```

**Comment by Alessandro-Barbieri** [comment]
@AndrewAmmerlaan could you try now?

**Comment by AndrewAmmerlaan** [comment]
> @AndrewAmmerlaan could you try now?

Still getting the same problem, rocm-cmake is installed. Note that I am testing with rocm*/hip* version 4.3.0 because my hardware is not supported by the newer versions.

**Comment by Alessandro-Barbieri** [comment]
@AndrewAmmerlaan it should work now but it doesn't pick up rocFFT
see also https://bugs.gentoo.org/836274

**Comment by Alessandro-Barbieri** [comment]
@littlewu2508 @justxi could you get a look?

**Comment by littlewu2508** [comment]
> @AndrewAmmerlaan it should work now but it doesn't pick up rocFFT see also https://bugs.gentoo.org/836274

which rocFFT version are you using? 5.0.2?

**Comment by Alessandro-Barbieri** [comment]
> which rocFFT version are you using? 5.0.2?

Yes

**Comment by littlewu2508** [comment]
Tested on ROCm-5.0.2 and it built OK. However, there is a warning:

```
One or more CMake variables were not used by the project:
HIPFFT_PATH
```

**Comment by littlewu2508** [comment]
> I'm getting the following configure error when I try to build with `USE="hip"`:
> 
> ```
> -- ROCclr at /usr/lib/cmake/rocclr
> -- hip::amdhip64 is SHARED_LIBRARY
> -- ROCclr at /usr/lib/cmake/rocclr
> -- hip::amdhip64 is SHARED_LIBRARY
> -- ROCclr at /usr/lib/cmake/rocclr
> -- hip::amdhip64 is SHARED_LIBRARY
> CMake Error at hip/CMakeLists.txt:246 (hip_add_library):
> Unknown CMake command "hip_add_library".
> 
> 
> -- Configuring incomplete, errors occurred!
> ```

I figured out the problem.

The ebuild specifies `-DHIP_PATH=/usr` but hip-4.3 is installed at `/usr/lib/hip`

**Comment by heroxbd** [comment]
> > @AndrewAmmerlaan could you try now?
> 
> Still getting the same problem, rocm-cmake is installed. Note that I am testing with rocm*/hip* version 4.3.0 because my hardware is not supported by the newer versions.

May I know what GPU are you using?  I could not find any hardware that is deprecated by ROCm 5 https://docs.amd.com/bundle/Deprecations/page/Deprecations_and_Warnings.html

**Comment by AndrewAmmerlaan** [comment]
> > > @AndrewAmmerlaan could you try now?
> > 
> > 
> > Still getting the same problem, rocm-cmake is installed. Note that I am testing with rocm*/hip* version 4.3.0 because my hardware is not supported by the newer versions.
> 
> May I know what GPU are you using? I could not find any hardware that is deprecated by ROCm 5 https://docs.amd.com/bundle/Deprecations/page/Deprecations_and_Warnings.html

RX590, the deprecation is not in version 5 but in version 4.5, see also:
https://github.com/RadeonOpenCompute/ROCm/issues/1608
https://github.com/RadeonOpenCompute/ROCm/issues/1659

**Comment by heroxbd** [comment]
@patricklauer Patrick, would you mind submitting a pull request on https://github.com/ROCm-Developer-Tools/ROCclr ? I don't have a gfx800 card to test with.

**Comment by AndrewAmmerlaan** [comment]
> Seems that the problem focus on OpenCL. Now ROCm provides OpenCL, but rocm-opencl-runtime drop gfx800 (Volcanic Islands, pre-vega) series support. For HIP components I see no compatibility issues. @AndrewAmmerlaan 

This is true but the different packages are all depending on one another and mixing different versions of things didn't really work when I tried earlier.

> Does [cbb1ec0](https://github.com/gentoo/gentoo/commit/cbb1ec071fdd7c549f89419cabf8330e204bbc32) solves the problem?

Yes it does, version 5.0.2 now properly detects my card. I'll test this PR again later. In any case we should probably depend on version >=5 of hip since it doesn't seem to work with 4.3.0.

**Comment by AndrewAmmerlaan** [comment]
> > Seems that the problem focus on OpenCL. Now ROCm provides OpenCL, but rocm-opencl-runtime drop gfx800 (Volcanic Islands, pre-vega) series support. For HIP components I see no compatibility issues. @AndrewAmmerlaan
> 
> This is true but the different packages are all depending on one another and mixing different versions of things didn't really work when I tried earlier.
> 
> > Does [cbb1ec0](https://github.com/gentoo/gentoo/commit/cbb1ec071fdd7c549f89419cabf8330e204bbc32) solves the problem?
> 
> Yes it does, version 5.0.2 now properly detects my card. I'll test this PR again later. In any case we should probably depend on version >=5 of hip since it doesn't seem to work with 4.3.0.

I tried to test this again but this time I got stuck on this bug: https://bugs.gentoo.org/857126

**Comment by littlewu2508** [comment]
> 
> I tried to test this again but this time I got stuck on this bug: https://bugs.gentoo.org/857126

clang-14 cannot compile hip/cuda code with gcc-12's stdc++. I will mask gcc-12 for sci-libs/roc-*

**Comment by AndrewAmmerlaan** [comment]
> > I tried to test this again but this time I got stuck on this bug: https://bugs.gentoo.org/857126
> 
> clang-14 cannot compile hip/cuda code with gcc-12's stdc++. I will mask gcc-12 for sci-libs/roc-*

With gcc-11 I still can't compile rocFFT, it just gives me a different error:
```
CMake Error at /usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:62 (message):
The C++ compiler

"/usr/bin/hipcc"

is not able to compile a simple test program.

It fails with the following output:

Change Dir: /var/tmp/portage/sci-libs/rocFFT-5.0.2-r1/work/rocFFT-rocm-5.0.2_build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/ninja cmTC_6f457 && [1/2] Building CXX object CMakeFiles/cmTC_6f457.dir/testCXXCompiler.cxx.o
[2/2] Linking CXX executable cmTC_6f457
FAILED: cmTC_6f457 
: && /usr/bin/hipcc -march=native -Wl,-O1 -Wl,--as-needed CMakeFiles/cmTC_6f457.dir/testCXXCompiler.cxx.o -o cmTC_6f457   && :
/usr/bin/x86_64-pc-linux-gnu-ld: /usr/lib64/libhsa-runtime64.so.1: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by littlewu2508** [comment]
> > > I tried to test this again but this time I got stuck on this bug: https://bugs.gentoo.org/857126
> > 
> > 
> > clang-14 cannot compile hip/cuda code with gcc-12's stdc++. I will mask gcc-12 for sci-libs/roc-*
> 
> With gcc-11 I still can't compile rocFFT, it just gives me a different error:
> 
> ```
> CMake Error at /usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:62 (message):
> The C++ compiler
> 
> "/usr/bin/hipcc"
> 
> is not able to compile a simple test program.
> 
> It fails with the following output:
> 
> Change Dir: /var/tmp/portage/sci-libs/rocFFT-5.0.2-r1/work/rocFFT-rocm-5.0.2_build/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):/usr/bin/ninja cmTC_6f457 && [1/2] Building CXX object CMakeFiles/cmTC_6f457.dir/testCXXCompiler.cxx.o
> [2/2] Linking CXX executable cmTC_6f457
> FAILED: cmTC_6f457 
> : && /usr/bin/hipcc -march=native -Wl,-O1 -Wl,--as-needed CMakeFiles/cmTC_6f457.dir/testCXXCompiler.cxx.o -o cmTC_6f457   && :
> /usr/bin/x86_64-pc-linux-gnu-ld: /usr/lib64/libhsa-runtime64.so.1: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
> clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
> ninja: build stopped: subcommand failed.
> ```

Hmm that means you have to keep the gcc version consistent: both rocr-runtime and rocFFT has to compile with gcc-11.

**Comment by AndrewAmmerlaan** [comment]
I'm really trying to properly test this, but I'm having a lot of trouble with the dependencies. Finally got rocBLAS to compile, now rocSOLVER fails :cry:  :https://bugs.gentoo.org/866839

**Comment by AndrewAmmerlaan** [comment]
> I'm really trying to properly test this, but I'm having a lot of trouble with the dependencies. Finally got rocBLAS to compile, now rocSOLVER fails cry :https://bugs.gentoo.org/866839

Okay this has been fixed, so I finally got around to testing this. I ran into the following configuration issue:
```
CMake Error at hip/CMakeLists.txt:135 (find_package):
Found package configuration file:

/usr/lib64/cmake/hiprand/hiprand-config.cmake

but it set hiprand_FOUND to FALSE so package "hiprand" is considered to be
NOT FOUND.  Reason given by package:

The following imported targets are referenced, but are missing:
roc::rocrand
```
Possibly we need to package `hipRAND` first?

**Comment by littlewu2508** [comment]
> Okay this has been fixed, so I finally got around to testing this. I ran into the following configuration issue:
> 
> ```
> CMake Error at hip/CMakeLists.txt:135 (find_package):
> Found package configuration file:
> 
> /usr/lib64/cmake/hiprand/hiprand-config.cmake
> 
> but it set hiprand_FOUND to FALSE so package "hiprand" is considered to be
> NOT FOUND.  Reason given by package:
> 
> The following imported targets are referenced, but are missing:
> roc::rocrand
> ```
> 
> Possibly we need to package `hipRAND` first?

Seems strange. hipRAND should be installed together with rocRAND, in ROCm-5.0.2, and you can see it found hiprand-config.cmake.

**Comment by littlewu2508** [comment]
@Alessandro-Barbieri I tried emerging ginkgo, but it compiles only for gfx803. Specifying `-DAMDGPU_TARGETS=<other archs>` does not help, either. Please find the way to configure  architecture, or users with other video card cannot use ginkgo hip feature.
