### PR TITLE
dev-python/m2crypto: add LibreSSL support

### PR DESCRIPTION
**Pull request by steils**
Closes: https://bugs.gentoo.org/674942
Package-Manager: Portage-2.3.54, Repoman-2.3.12
Signed-off-by: Stefan Strogin <stefan.strogin@gmail.com>

### CODE REVIEW

**Comment by steils** [comment]
Tried to build with libressl-2.7.5, got this:

```
 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * SWIG/_m2crypto_wrap.c:5760:11: warning: implicit declaration of function ‘OPENSSL_zalloc’; did you mean ‘OPENSSL_malloc’? [-Wimplicit-function-declaration]
 * SWIG/_m2crypto_wrap.c:5783:32: warning: implicit declaration of function ‘BIO_get_init’; did you mean ‘BIO_set_init’? [-Wimplicit-function-declaration]
 * SWIG/_m2crypto_wrap.c:5760:11: warning: implicit declaration of function ‘OPENSSL_zalloc’; did you mean ‘OPENSSL_malloc’? [-Wimplicit-function-declaration]
 * SWIG/_m2crypto_wrap.c:5783:32: warning: implicit declaration of function ‘BIO_get_init’; did you mean ‘BIO_set_init’? [-Wimplicit-function-declaration]
```

**Comment by steils** [comment]
Seems fixed.

**Comment by steils** [comment]
Unfortunately m2crypto's author is rather unfriendly to LibreSSL: https://gitlab.com/m2crypto/m2crypto/merge_requests/139
So right now I don't have inspiration to try to upstream it.
