### PR TITLE
net-misc/dahdi: Fix build with clang-16 and migrate to linux-mod-r1 e…

### PR DESCRIPTION
**Pull request by listout**
…class

Ran into -Werror issues (silly stuff like implicit fallthrough), but -Werror is no longer passed with linux-mod-r1. Not that this stops ones like the -Werror=incompatible-pointer-types wrt bug #906179, so that issue still applies when using kernel 6.3(?). Was fine with a stable 6.1.28 gcc-13 kernel, albeit ftr it still failed with a clang-16 one giving:

dahdi-linux-3.2.0/drivers/dahdi/wctc4xxp/base.c:646:9: error:
      passing 'const unsigned char *' to parameter of type 'void *'
      discards qualifiers
      [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        memcpy(netdev->dev_addr, our_mac, sizeof(our_mac));

fwiw MODULES_ARGS+=( KCFLAGS=-Wno-error=incompatible-pointer-types ) lets it build with both 6.3.4 kernel-bin (gcc) and 6.1.28 (clang+lto), not that this is a great fix and may hide more notable issues (may be better than being semi-unbuildable for now though)

wrt old depmod find, should not be necessary given eclass adds DEPMOD=:

The patch fixes some -Wincompatible-pointer-types-discards-qualifiers, thus making it possible to built with clang-16.

Closes: https://bugs.gentoo.org/906179

### CODE REVIEW

**Comment by jkroonza** [comment]
I'll add the patch to the archive.  Having tried the same though ... does this work with gcc still?

**Comment by thesamesam** [comment]
> Haven't checked it, will do.

ping

**Comment by listout** [comment]
> ping

Sorry for the late reply. Still haven't (properly) checked. Just wanted to note that the upstream PR have been merged.

https://github.com/asterisk/dahdi-linux/pull/21

**Comment by jkroonza** [comment]
> > ping
> 
> Sorry for the late reply. Still haven't (properly) checked. Just wanted to note that the upstream PR have been merged.
> 
> [asterisk/dahdi-linux#21](https://github.com/asterisk/dahdi-linux/pull/21)

Thanks.  Do you actively use dahdi or know of anyone that does?  My last use-cases went away and I'm contemplating dropping net-misc/{dahdi,dahdi-linux} completely.

**Comment by listout** [comment]
Unfortunately not. I came across this gentoo bug from the gentoo modern c porting tracker
